### ISSUE TITLE
Custom nodes may silently output incomplete/incorrect pipeline definitions

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#1]
The `definition` property of a `node` is used to output a human-readable and human-editable pipeline definition. It is defined for the main node types `DataSource`, `Compositor`, and `Algorithm`.

In some node subclasses, the default (parent) definition is sufficient and does not need to be reimplemented, but subclasses that use additional attributes will need to overwrite or extend the definition. For example, the `definition` property is extended in some `datalib.smap` nodes.

Nodes that do *not* reimplement the `definition` may *silently* output pipeline definitions that are incorrect due to missing attributes. This applies to existing podpac nodes that do not yet reimplement the property, nodes that are be added to podpac in the future, and custom nodes created by podpac users.

It is not yet clear what a solution to this would look like.

**Comment by mpu-creare** [comment]
I believe this is fixed by #55 . @jmilloy do you concur?

**Comment by jmilloy** [comment]
Yes.
