### ISSUE TITLE
*Proposal*: Parse sub-attributes in Pipelines

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#10]
We want to be able to reference
 * node sub-attributes specifically in Algorithm `inputs` and Compositor `sources`
 * sub-attributes generally in `attrs`

e.g.

```
{
    "nodes": {
        "downscaled_sm_algorithm": {
            ...
       },
       "reprojected": {
            "node": "core.data.type.ReprojectedSource"
            "inputs": {"source": "downscaled_sm_algorithm.twi"}
            "attrs": {"reprojected_coordinates": "downscaled_sm_algorithm.solmst.native_coordinates"}
       }
    }
}
```

This is just a proposal for now, and needs to be thought through more carefully and discussed.

**Comment by jmilloy** [comment]
@mpu-creare This looks long, but I don't think it will take you long to answer my question.

Currently we parse data values (string, number, boolean, list, dictionary) in all node definitions from "attrs" and "params". We also translate string references to previous nodes in the pipeline in two cases: "inputs" in Algorithm nodes and "sources" in Compositor nodes. These two cases need to be handled separately.

*Would you pick one of the following for each? My choice is either (1/1) or (2/4).*

**Proposals for attrs/params**

1. Use a dictionary with "node" and "attr" properties, and otherwise disallow dictionary values.


```
"nodes": {
    "downscaled_sm_algorithm": { ... },
    "reprojected": {
        "node": "core.data.type.ReprojectedSource",
        "attrs": {
            "reprojected_coordinates": {"node": "downscaled_sm_algorithm", "attr":"solmst.native_coordinates"},
            "interpolation": "bilinear",
            "another_attr": {"a": 1, "b": 2} <----- this would fail
        }
    }
}
```

2. Use another property, such as "subattrs" or "node_attrs", and disallow periods in node names


```
"nodes": {
    "downscaled_sm_algorithm": { ... },
    "reprojected": {
        "node": "core.data.type.ReprojectedSource",
        "attrs": {
            "interpolation": "bilinear",
            "another_attr": {"a": 1, "b": 2} <----- this would work
        },
        "subattrs": {
            "reprojected_coordinates": "downscaled_sm_algorithm.solmst.native_coordinates"
        }
    },
    "my.other.node": { ... } <----- this would fail
}
```

3. Use another property *and* a dictionary with "node" and "attr" properties (allowing periods in node names)


```
"nodes": {
    "downscaled_sm_algorithm": { ... },
    "reprojected": {
        "node": "core.data.type.ReprojectedSource",
        "attrs": {
            "interpolation": "bilinear",
            "another_attr": {"a": 1, "b": 2} <----- this would work
        },
        "subattrs": {
            "reprojected_coordinates": {"node": "downscaled_sm_algorithm", "attr":"solmst.native_coordinates"}
        }
    },
    "my.other.node": { ... } <----- this would work
}
```

**Proposals for input/sources**

1. Use a dictionary with "node" and "attr" properties (similar to 1 above):


```
"nodes": {
    "downscaled_sm_algorithm": { ... },
    "my_other_input": { ... },
    "my_algorithm": {
        "inputs": {
            "twi": {"node": "downscaled_sm_algorithm", "attr":"twi"},
            "other": "my_other_input"
        }
    }
}
```

2. Use another property, such as "subinputs" or "node_inputs", and disallow periods in node names (simlar to 2 above):

```
"nodes": {
    "downscaled_sm_algorithm": { ... },
    "my_other_input": { ... },
    "my_algorithm": {
        "inputs": {
            "other": "my_other_input"
        }
        "subinputs" {
            twi": "downscaled_sm_algorithm.twi",
        }
    }
}
```

3. Use another property *and* a dictionary (similar to 3 above)

```
"nodes": {
    "downscaled_sm_algorithm": { ... },
    "my_other_input": { ... },
    "my_algorithm": {
        "inputs": {
            "other": "my_other_input"
        }
        "subinputs" {
            "twi": {"node": "downscaled_sm_algorithm", "attr":"twi"},
        }
    }
}
```

4. Just use strings, and disallow periods in node names:

```
"nodes": {
    "downscaled_sm_algorithm": { ... },
    "my_other_input": { ... },
    "my_algorithm": {
        "inputs": {
            "twi": "downscaled_sm_algorithm.twi",
            "other": "my_other_input",
        }
    }
}
```

**Comment by jmilloy** [comment]
@mpu-creare 

Altogether, 1/1 looks like this (but you can't set dictionary attrs in pipelines):

```
"nodes": {
    "downscaled_sm_algorithm": { ... },
    "my_other_input": { ... },
    "my_algorithm": {
        "inputs": {
            "twi": {"node": "downscaled_sm_algorithm", "attr":"twi"},
            "other": "my_other_input"
        },
        "attrs" {
             "attr1": 10,
             "attr2": {"node": "downscaled_sm_algorithm", "attr": "solmst.native_coordinates"}
        }
    }
}
```

**Comment by jmilloy** [comment]
@mpu-creare 

And 2/4 looks like this (but you can't use periods in node names):

```
"nodes": {
    "downscaled_sm_algorithm": { ... },
    "my_other_input": { ... },
    "my_algorithm": {
        "inputs": {
            "twi": "downscaled_sm_algorithm.twi"},
            "other": "my_other_input"
        },
        "attrs" {
            "attr1": 10
        },
        "subattrs" {
            "attr2": "downscaled_sm_algorithm.solmst.native_coordinates"
    }
}
```

**Comment by jmilloy** [comment]
@mpu-creare 

The final option 3/3 is the least restrictive but the most cumbersome.

They are all about the same effort in the implementation.

**Comment by mpu-creare** [comment]
I like the fact that there's a nice 1:1 match between json and python for (`string`, `number`, `boolean`, `list`, `dictionary`) , so I don't like disallowing dictionaries. Particularly because I suspect that will catch some people off guard. 

I've been thinking about this from the Python side. 

```python
class Test(Node):
     a_node = tl.Instance(Node).tag(attr=True)
     b_node = tl.Instance(Node).tag(param=True)
     attr = tl.AnyJson().tag(attr=True)
     param = tl.AnyJson().tag(param=True)
```
And this can get translated to: 
```json
"nodes": {
    "test": {
        "node": <Podpac_Node_Type>,
        "attrs": {"attr": <Attr_value>},
        "params": {"attr": <Param_value>},
        "node_attrs": {"a_node": "path.to.node.or.node.attr"},
        "node_params": {"b_node": "path.to.node.or.node.param"}
    }
}
```
which is nice, because on the Python side you don't have to distinguish one type of `attr` from another. 

So basically the problem needs fixing on the JSON side, because JSON doesn't support a podpac node type. As such, we need a special section to tell the JSON that we actually want a podpac node type... that's how I've been thinking about it. 

So I think this is the same as 2/4 and 1/2, which disallows periods in node name -- which I'm fine with. 

I suppose if you REALLY wanted to have periods  you could do: `"node_attrs": ['path.with.dots', 'to', 'node', 'or', 'node', 'attr']`, where the first element of the list is the node, and anything past that is an attribute of some sort, but I'd like to discourage that... in fact, we could probably implement this on top of 2/4 if we ever wanted to do so (i.e. if a use case comes up) [i.e. if the type is a string assume the first part is a node name. If the type is list, the first element is a node name. If the type is a dict... something?, basically the extra sections gives us a lot of flexibility.). 

We can also chat about this.

**Comment by jmilloy** [comment]
@mpu-creare @mlshapiro 

I'm trying to wrap this one real quick. I'm not doing anything now regarding serialize/deserialize the interpolation property, but there is an issue with it that I need to clean up. In the pipeline node definition for a datasource, should the interpolation be in the "attrs" or top-level?

    "nodes": {
        "my_data_source": {
            "node": "MyDataSource",
            "source": "my_source",
            "interpolation": "nearest",
            "attr": {
                "my_attr": 10
            }
    }

or

    "nodes": {
        "my_data_source": {
            "node": "MyDataSource",
            "source": "my_source",
            "attr": {
                "interpolation": "nearest",
                "my_attr": 10
            }

**Comment by mpu-creare** [comment]
It's complex enough an inherent enough that I think it should go top-level.

**Comment by jmilloy** [comment]
Okay, that's fixed here: dc8d8fa

**Comment by jmilloy** [comment]
@mpu-creare The ReprojectedSource `coordinates_source` is any Node but it uses `coordinates_source.native_coordinates`. I don't know enough about ReprojectedSource usage -- should I update `coordinates_source` to be specifically a DataSource, or should I update ReprojectedSource to use `coordinates_source.find_coordinates` instead of `coordinates_source.native_coordinates`?

**Comment by mpu-creare** [comment]
That should specifically be a `DataSource` node.

**Comment by jmilloy** [comment]
d728317

I know it doesn't exactly belong to the sub_attributes feature branch, but it's fixed there.
