### ISSUE TITLE
Dependent/Rotated/Calculated Coordinates

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#102]
There is a stub for this, but it is not yet implemented.

**Comment by jmilloy** [comment]
The rotated coordinates will be a special case for parameterized (non-regular) coordinates.

Can this be limited to spatial (lat-lon) coordinates or does it need to be general?

**Comment by mpu-creare** [comment]
Spatial lat-lon will be fine, because that will cover the GDAL transform case, which is what we're trying to cover. 

We should discuss the details of this at some point... there are a couple of considerations for:
- metadata
- re-opening files
- saving files

**Comment by mpu-creare** [comment]
Potential Issues: 
* Need to think about serialization... does to_netcdf still work? 
* Need to include metadata to reconstruct gdal transform
* Rotated coordinates should probably use the gdal transform under the hood, or the rasterio affine map
* When intersection or sub-selecting, preserve the underlying index of the array (i.e. original goes from 0-10, subselect goes from 2-5)

**Comment by mpu-creare** [comment]
A few more thoughts: 
* A DependendCoords (similar to StackedCoords) class might be helpful
* it might be nice to have a link between the two dependent coordinates (from one to the other). 
    * In the rotated coordinates case, perhaps these will share the affine mapping (i.e. change the affine mapping in one changes the other...)

**Comment by jmilloy** [comment]
* We will use what xarray calls [non-dimension coordinates](http://xarray.pydata.org/en/stable/data-structures.html#coordinates) with underlying dimension coordinates 'i', 'j', 'k', and 'l' as needed as indexes.
 * We could use non-dimension coordinates for the StackedCoordinates as well (instead of the MultiIndex). This is just a note for future reference.
 * Currently there is a nice 1-1 mapping in Coordinates objects between its coords objects and its dimensions (ie, two coords objects means two dimensions, whether it is two Coordinates1d objects or one Coordinates1d object and one StackedCoordinates object). A DependentCoordinates object could be helpful in linking several dependent coordinates, but comes at a cost of breaking this 1-1 mapping.
    - For example, currently we can get intersection indices with `I = [c.intersect(other, return_indices=True)[1] for c in self.coords.values()]`, and `I` can be used directly to index a corresponding DataArray. With a `DependentCoordinates` object, `I` would need to be properly flattened first.
    - On the other hand, without linked dependent coordinates, methods like `drop` will require additional checks. In coordinates containing a rotated lat-lon grid, the `lat` dimension cannot be dropped without also dropping the `lon` dimension. Maybe the easy restriction is that individual dependent coordinates cannot be dropped, but with a linked `DependentCoordinates` object, these sorts of checks and manipulations can be made more easily.

**Comment by jmilloy** [comment]
* I don't think there is a way to do the necessary intersections without some shared state in dependent coordinates. I interested in the idea of say two separate objects (lat and lon dependent coordinates) with a shared affine mapping, but a RotatedCoordinates object may be a better choice.

**Comment by jmilloy** [comment]
@mpu-creare How do you want to create rotated coordinates? I think we need 7 arguments:
 
* theta, upper left lat and lon, bottom right lat and lon, and shape (in each direction)
* theta, upper left lat and lon, bottom right lat and lon, and step (in each direction)
* theta, upper left lat and lon, shape (in each direction) and step (in each direction)

I will use an [Affine object](https://github.com/sgillies/affine) (which rasterio uses) under the hood either way. We could also create the rotated coordinates with this object directly (6-elements), but we would still need shape and step in each direction, so that would become 10 arguments.

**Comment by mpu-creare** [comment]
What would `step` be in the examples above? Isn't that the underlying index of the array? Or would it be a (lat,lon) tuple (for each direction of the array). 

Anyway, based on my question I think option 1 makes the most sense (no step specification involved = no confusion). Note, this is over-specified for pure-rotation, but it also covers the case for skew... which is great. 

Also, the ability to create the mapping from the Affine object directly + shape makes sense. I'm not sure what the `step` would do in that case as well. 

My understanding is that the affine mapping works as follows:
```math
(lat, lon) = A * (i, j, 1)
```
where (i, j) are the indices of the underlying array, and "*" is a matrix multiplication

**Comment by jmilloy** [comment]
> Also, the ability to create the mapping from the Affine object directly + shape makes sense.

Yep, a lot of sense. Great.

**Comment by jmilloy** [comment]
I guess we need to support segment ctypes and segment lengths. I may skip that in the first pass and only do 'point' coordinates. But: I assume that segments are rotated as well. The segment lengths gets a bit back into "what is step" territory. I think the segment length and the step is the same -- the horizontal or vertical distance between adjacent coordinates before rotation, which is preserved when rotated and translated.

> What would step be in the examples above? Isn't that the underlying index of the array? Or would it be a (lat,lon) tuple (for each direction of the array).

I think it's neither. If the shape is (4, 3) and the step is (2, 4), I would use `i = [0, 1, 2, 3]` and `j = [0, 1, 2]` as the underlying index and then scale+rotate+translate, where the step provides the scale.

```
ulc = (10, 20)
shape = (4, 3)
step = (2, 4)
theta = 30.0

a = Affine.translation(ulc) * Affine.rotation(deg) * Affine.scale(step)
i = np.arange(shape[0])
j = np.arange(shape[1])
x = np.meshgrid(i, j)
lat, lon = a * x
```

Given the `lrc` instead of the `step`, I'd just calculate the step/scale anyways.

As far as segments, I'm assuming that they are also rotated and the default segment lengths would be uniform and equal to the step (as opposed to unrotated lat and lon segment lengths).

**Comment by jmilloy** [comment]
I'm also keeping other dependent coordinates in mind here, such as polar coordinates. It is possible that the NEXRAD coordinates are actually spherical, with an altitude component that is stacked with the radius.

**Comment by mpu-creare** [comment]
Ah! Now the step makes sense, as part of a  scale factor... 

The way gdal's transform works is by specifying dlat/di, dlat/dj, dlon/di, and dlon/dj ... and I think those are essentially the entries in the matrix (plus the offset). 

So I suppose the scale then specifies the scaling
* i2units and
* j2units,

 where **units** are usually in degrees for us, but could be meters, or feet, depending on the geospatial coordinates used... 

And yes, we'd have to support `ctype` and `segment length` -- but the latter should always be calculable using the specified function. For example, f(i, j) - f(i+1, j) will give you the segment length in the i direction.

oOoh, my brain hurts. We want the segment lengths for intersections... so when doing an intersection you probably have to work in real space -- and then you'll be interested in the segment length in the lat direction for example... I'll let you think about it more carefully.

**Comment by mpu-creare** [comment]
Thanks for keeping NEXTRAD in mind as well.

**Comment by jmilloy** [comment]
I'm optimistic about [GDAL integration](https://github.com/sgillies/affine#usage-with-gis-data-packages).

```
>>> geotransform = (-237481.5, 425.0, 0.0, 237536.4, 0.0, -425.0)
>>> fwd = Affine.from_gdal(*geotransform)
>>> col, row = 0, 100
>>> fwd * (col, row)
(-237481.5, 195036.4)
>>> rev = ~fwd
>>> rev * fwd * (col, row)
(0.0, 99.99999999999999)
```

And there is `Affine.to_gdal` as well.

**Comment by jmilloy** [comment]
@mpu-creare Do the rotated coordinates ever need to be 3-dimensional (ie lat, lon, and alt), or can they always be either (lat, lon) or (lon, lat)?

**Comment by mpu-creare** [comment]
Since this class is really to support the gdal functionality that we're currently missing, lat-lon only is fine. If we ever have a use-case for lat-lon-alt, then we can modify, or write a new class. 

So no, only 2-D.

**Comment by jmilloy** [comment]
Just as an update

The `RotatedCoordinates` object contains the rotated coordinates system and is created with a shape, theta, ulc, and lrc/step:

```
rot = RotatedCoordinates(shape=(10, 15), theta=np.deg2rad(30), ulc=(10, 20), lrc=(30, 50), dims=['lat', 'lon'])
```

Some key properties and methods:
 * `rot.affine`: the Affine transformation object
 * `rot.geotransform`: the gdal geotransform tuple
 * `rot.coordinates`: a tuple of 2d arrays for the latitude and longitude coordinates
 * `rot.intersect(...)`: returns a `RotatedCoordinates` object and, if return_indices is True, a pair of slices
 * indexing
    - `rot[0:5, 1:6:2]: returns a `RotatedCoordinates` object
    - `rot[[1, 3, 2], [1, 0]]: returns a generic `DependentCoordinates` object
    - `rot['lat']`: returns the lat portion only

You will usually create RotatedCoordinates like this, though, so that it's easy to make a Coordinates object:

```
lat, lon = RotatedCoordinates(shape=(10, 15), theta=np.deg2rad(30), ulc=(10, 20), lrc=(30, 50), dims=['lat', 'lon'])
c = Coordinates([lat, lon, ['2018-01-01', '2018-01-02']], dims=['lat', 'lon', 'time'])
```

The `lat` and `lon` objects above are `DependentCoordinatesItem` objects, which subclass BaseCoordinates and wrap the necessary attributes and methods: `name`, `coordinates`, `coords`, `intersect`, etc. We'll never be instantiating these objects directly, but they allow Coordinates to maintain a 1-1 mapping of (xarray) dimensions to `BaseCoordinates` objects.

A few other notes:

 * The `Coordinates` class has an import property `coords` that makes the corresponding xarray coords, and that has been rewritten to handle Coordinates1d, StackedCoordinates, and DependendentCoordinatesItem at the same time.
 * The DependentCoordinates class factors out a lot and will make it very easy for us to implement the PolarCoordinates.
    - generic `DependentCoordinates` are really the same as StackedCoordinates but with a multidimensional shape.
 * Currently you can create lat-lon or lon-lat versions of RotatedCoordinates. I haven't quite figured out if that makes sense or not.
