### ISSUE TITLE
check stacked coordinates length on creation

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#105]
**Description**
When creating stacked coordinates, I don't get an error when using arrays of different lengths. I get the error the first time I try to call any property or method on the coordinates.

This may be by design, I just mention it here in case it is not by design.

**Steps to Reproduce**
```
from podpac.core.coordinates import Coordinates

stacked = Coordinates( [ ([1,2,3,4,5], [0,1,2,3]) ], dims=['lat_lon'])  # i expect error here
stacked.coords  # I get error here

```

**Expected Behavior**

```
stacked = Coordinates( [ ([1,2,3,4,5], [0,1,2,3]) ], dims=['lat_lon'])  # i expect ValueError here
```

**Comment by jmilloy** [comment]
Thanks, fixed here 8a92233
