### ISSUE TITLE
Wrap GPM Precipitation

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#106]
**Description**
Write class to provide access to [GPM precipitation](https://pmm.nasa.gov/data-access/downloads/gpm)

**Describe the solution you'd like**
Write a wrapper similar to the SMAP wrapper, starting with [one of the data products (GPM_3IMERGHHE.05)](https://gpm1.gesdisc.eosdis.nasa.gov/opendap/hyrax/GPM_L3/GPM_3IMERGHHE.05/contents.html)

**Sample Code**
```
from podpac.datalib.GPM import GPM
gpm = GPM(product='3IMERGHHE.05')
o = gpm.eval(...)
o.plot()
```

**Additional context**
We'd like to have precipitation data so that we can compare it to the soil moisture signal produced by SMAP to see if they correlate

**Comment by mlshapiro** [comment]
First example: https://gpm1.gesdisc.eosdis.nasa.gov/opendap/hyrax/GPM_L3/GPM_3IMERGHHE.05/contents.html

**Comment by mpu-creare** [comment]
Done under Soilmap
