### ISSUE TITLE
Difference between .coords and .coordinates

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#130]
**Description**
Question: What is the difference between the .coords on ArrayCoordinates1D and .coordinates properties on Coordinates1D? 

From the spec for Coordinates1D:

```markdown
- `coordinates`: read-only array
```

From the spec for ArrayCoordinates1D:

```markdown
Traits:
 - `coords`: array
```

**Comment by jmilloy** [comment]
The `coordinates` is a common read-only property of all Coordinates1d.

ArrayCoordinates1d uses `coords` trait to maintain its coordinate values, just like UniformCoordinates1d uses `start`, `stop`, and `step` for its coordinate values. Each implements the `coordinates` property, which of course returns a copy of the `coords` for ArrayCoordinates1d.

If you want to change the coordinates of an ArrayCoordinates1d, you can use `c.coords = [0, 1, 2]` but not `c.coordinates = [0, 1, 2]`.

**Comment by jmilloy** [comment]
We could make the `coords` private if you want (but probably not `start`, `stop` and `step`).

**Comment by mlshapiro** [comment]
perfect - thank you for the explanation. I will add this explanation to the spec. 

I ended up making some notebooks for each of these classes so that I don't have to keep writing examples as I'm trying to develop. Thats where these questions are coming from, mostly just trying to understand.

**Comment by jmilloy** [comment]
My understanding was that the developer specs would be abandoned once implemented and eventually removed, in favor of the user guides and docstrings, and that @mpu-creare advised us not to worry about maintaining the dev specs if the implementation deviated. The coordinates user guide and docstrings are not complete (#45, #4) but should be soon; I'd put updates for clarification in those locations.
