### ISSUE TITLE
the pipeline definition of `podpac.core.data.types.Array` can not be converted to json

### ISSUE THREAD

**Issue by drc-creare** [creare-com/podpac#131]
**Description**
`Array` type node pipeline definition can not be converted to json because `numpy.ndarray` can not be converted to json.

**Steps to Reproduce**
```
from podpac.core.data.types import Array
from podpac.core.coordinates.coordinates import Coordinates

lat = [0, 1, 2]
lon = [10, 20, 30, 40]
dates = ['2018-01-01', '2018-01-02']
native_coordinates = Coordinates([lat,lon,dates],['lat','lon','time'])
source = np.zeros(native_coordinates.shape)
array_data_source = Array(source=source, native_coordinates=native_coordinates)
array_data_source.json
```

**Expected Behavior**
I would have expected this nodes pipeline definition to be json serializeable. That said, this is going to be difficult to achieve in all cases. `UnitsDataArray` are also not JSON serializable for example.

**Observed Behavior**
`array_data_source.json` throws an error:

```
In [14]: array_data_source.json
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-a3453bb57998> in <module>()
----> 1 array_data_source.json

/mnt/c/Creare_Data/Projects/Pipeline/code/p2/podpac/podpac/core/node.py in json(self)
    353         share algorithms and pipelines, or run code on cloud services.
    354         """
--> 355         return json.dumps(self.definition, indent=4)
    356
    357     @property

~/anaconda3/envs/podpac3/lib/python3.6/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237         separators=separators, default=default, sort_keys=sort_keys,
--> 238         **kw).encode(obj)
    239
    240

~/anaconda3/envs/podpac3/lib/python3.6/json/encoder.py in encode(self, o)
    199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
--> 201             chunks = list(chunks)
    202         return ''.join(chunks)
    203

~/anaconda3/envs/podpac3/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    428             yield from _iterencode_list(o, _current_indent_level)
    429         elif isinstance(o, dict):
--> 430             yield from _iterencode_dict(o, _current_indent_level)
    431         else:
    432             if markers is not None:

~/anaconda3/envs/podpac3/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3/envs/podpac3/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3/envs/podpac3/lib/python3.6/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    402                 else:
    403                     chunks = _iterencode(value, _current_indent_level)
--> 404                 yield from chunks
    405         if newline_indent is not None:
    406             _current_indent_level -= 1

~/anaconda3/envs/podpac3/lib/python3.6/json/encoder.py in _iterencode(o, _current_indent_level)
    435                     raise ValueError("Circular reference detected")
    436                 markers[markerid] = o
--> 437             o = _default(o)
    438             yield from _iterencode(o, _current_indent_level)
    439             if markers is not None:

~/anaconda3/envs/podpac3/lib/python3.6/json/encoder.py in default(self, o)
    178         """
    179         raise TypeError("Object of type '%s' is not JSON serializable" %
--> 180                         o.__class__.__name__)
    181
    182     def encode(self, o):

TypeError: Object of type 'ndarray' is not JSON serializable
```

**Additional Notes**
I was going to use `node.json` to get a hash of a node's pipeline definition for caching. I am going to switch to using pickle to serialize `node.definition` instead (for now).

**Comment by drc-creare** [comment]
@jmilloy not sure if you are the right one to assign this. @mpu-creare node.json (json version of pipeline definition) will probably often cause problems. A lot of things are not json serializable (e.g. numpy.ndarray for instance). I'm not sure if xarray is.

**Comment by jmilloy** [comment]
This is an easy fix. In general, we expect node attrs to be simple and serializable values that users can type out in json format. I believe that the Array `source` and the ReprojectedSource `reprojected_coordinates` are the only two exceptions, and we can easily serialize those two types.

@mpu-creare The DataSource source is sometimes tagged as an attr and sometimes not. I need to fix that now. Which is it supposed to be? I believe it should *not* be tagged, ie the first, but either way will work.

```
nodes: {
    "a": {
        "node": "MyDataSource",
        "source": "my source"
    }
}
```

or

```
nodes: {
    "a": {
        "node": "MyDataSource",
        "attrs" {
            "source": "my source"
        }
    }
}
```

**Comment by drc-creare** [comment]
Thanks @jmilloy that does sound like a pretty straight forward fix. Have a good weekend.

**Comment by jmilloy** [comment]
At the same time, I don't think using the hash of the pickled definition instead of the json definition is a bad idea. There will always be the possibility of attrs that can't be serialized; maybe those custom nodes won't be usable in a pipeline or AWS, but their results could still be cached.

**Comment by mpu-creare** [comment]
I agree that the source should not be tagged. Basically because we know every datasource has to have a source anyway (otherwise it's not a datasource). But what do we do if it's also tagged?

I suppose we should always check if source or an attr is a serializable type, and if not, throw some sort of warning or exception. 

As part of that check, we can have a few types that we know how to serialize. And yes, I agree that ndarray (`arr.tolist()`)  and coordinates (`coord.json`) should be easy to serialize. 

Caching based on the the pickled definition hash sounds like a pretty good idea! Very nice way of getting around this issue in the general case. Although, I suppose not everything is picklable either... but certainly more things can be pickled compared to jsonalized.

**Comment by jmilloy** [comment]
3235564
