### ISSUE TITLE
Nearest neighbor select_coordinates and interpolate on stacked coordinates

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#133]
**Description**

Currently we don't support any stacked dimensions for nearest neighbor interpolation.

**Describe the solution you'd like**

1. Interpolate dimensions that are not stacked even if other stacked dimensions exist in coordinates
2. Perform an actual multi-dim nearest neighbor (find the stacked dimension with the nearest point and use that)

**Comment by jmilloy** [comment]
@mlshapiro @mpu-creare Can you clarify this for me? Which of the cases does this issue cover

 - unstacked source coordinates, stacked eval coordinates
 - stacked source coordinates, unstacked eval coordinates
 - stacked source coordinates, stacked eval coordinates

**Comment by mpu-creare** [comment]
I believe this covers the last two cases:
* stacked source coordinates, unstacked eval coordinates
* stacked source coordinates, stacked eval coordinates

**Comment by mpu-creare** [comment]
This will be fixed in #430.
