### ISSUE TITLE
Integrate refactored cache into Node class.

### ISSUE THREAD

**Issue by drc-creare** [creare-com/podpac#140]
**Description**
Integrate refactored cache into Node class. This means implementing the stubs in Node for cache operations and instantiating a default cache controller that is imported by Node.

**Comment by mpu-creare** [comment]
Please also rename `del` to `rem` in `Node`

**Comment by jmilloy** [comment]
I have a branch with the output caching decorator. Do you need that in the 0.2.0 release or is 0.2.1 okay?

**Comment by drc-creare** [comment]
Thanks @jmilloy ! I am targeting 0.2.1 for Node/cache integration, so 0.2.1 should be ok for this.

**Comment by mpu-creare** [comment]
0.2.1 please

**Comment by mpu-creare** [comment]
This was done in #175
