### ISSUE TITLE
Add clinspace and crange to Coordinates notebook

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#149]
**Description**
The [Coordinates](https://github.com/creare-com/podpac/blob/develop/doc/notebooks/developer/Coordinates.ipynb) developer notebook describes how to use Coordinates, but it doesn't include a description for creating 1D coords objects using clinspace and crange. MOreover, it's not clear why you would use clinspace over linspace, and crange over range. 

**Describe the solution you'd like**
Some examples and explanation for crange and clinspace

**Comment by jmilloy** [comment]
There is a lot of duplicate information in the User Guides and the notebooks. Do we really need both? Can we do away with the User Guides in favor of the notebooks?

**Comment by mpu-creare** [comment]
Yes. Notebooks in favor of User Guides. The User Guides should link to the notebooks.
