### ISSUE TITLE
Add ability to automatically deal with different CRS and Projections

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#152]
**Description**
One of PODPAC's core features is to automatically deal with geospatial coordinate reference systems and projections in a seamless manner. Right now, all of the datasets have to be in the same CRS and have the same units to work together (interpolation is automatic). 

**Describe the solution you'd like**
Need a mechanism to:
* [ ] specify the `proj4` CRS in coordinates
* [ ] automatically convert CRS in one dataset to the requested CRS

**Comment by jmilloy** [comment]
See also #103

**Comment by jmilloy** [comment]
Note: I've enforced that all 1d coordinates in a Coordinates be the same crs in #163

**Comment by mlshapiro** [comment]
@mpu-creare i am overestimating the time on this one because i think this is one of the more important features to get right. This will be the first thing I work on starting this week.

**Comment by mlshapiro** [comment]
Seems like we use `crs` and `coord_ref_sys` in the coordinates and node objects. Based on proj4 and rasterio, I am going to change these references to `crs` and refer the coordinate `coord_ref_sys` to self.crs

**Comment by mlshapiro** [comment]
hm on second thought, `coord_ref_sys` is everywhere. i'm going to keep this for now and refer `crs` to `coord_ref_sys`.

After @jmilloy finishes the coordinates updates, I will merge those in and then make the vernacular change to `crs`
