### ISSUE TITLE
Automatically deal with unit conversion in Coordinates

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#153]
**Description**
A core feature of PODPAC is to automatically handle unit differences in Coordinates. This is not currently implemented. 

**Describe the solution you'd like**
We need a mechanism: 
* [x] To assign units to coordinates that doesn't class with CRS for lat-lon
* [x] To automatically do unit conversions when interpolating datasets

**Comment by jmilloy** [comment]
See also #103

**Comment by mlshapiro** [comment]
as far as I can tell this has been implemented in #152. May need a little refinement in #244

**Comment by jmilloy** [comment]
This is indeed completed with #244.
