### ISSUE TITLE
DISCUSSION: Should we create an "examples" repository for files? 

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#157]
* I really want to put more relevant examples into PODPAC (instead if always using generated data). 
* I don't want to bloat the code with large geotiffs, csvs, etc. 

The way I've seen others solve this problem (i.e. OpenFOAM) is to create a second repository with example files. So the second repository is large and bloated, but the primary code repository remains lean. 

* What do y'all think about that? 
* What about testing? Can we leverage this for testing as well? 

If I don't hear any objections I'm doing it.

**Comment by mlshapiro** [comment]
I think this makes a lot of sense. Is there a reason you structured the examples as a python module?  I think its fine to just have a repository of python scripts/notebooks organized with directories as each example.

**Comment by mpu-creare** [comment]
I made a module so we could eventually pip install. Also, it makes it easier to deal with paths. All our notebooks can work by using the same function to figure out the path of the example files. Otherwise, we could ask users to unpack the examples in the same directory every time... but that seems more fragile.

**Comment by mpu-creare** [comment]
I had a chat with @jbieszcz . 

The plan is to put ALL of the examples and their data in the podpac_examples repo. This will keep the code repo nice and lean, and allows to put large files with the examples in one place. 

Anyone else want to weigh in? Otherwise I'll close this soon.

**Comment by drc-creare** [comment]
Sounds good!

**Comment by jmilloy** [comment]
Will these examples be available for testing? In particular, could/would/should the **podpac/core/pipeline/test/test.json** file be moved to the podpac_examples repo? The examples would be required for some tests to pass, but those tests would be skipped to be skipped if the examples repo wasn't available).

**Comment by jmilloy** [comment]
Yes, that makes sense.

**Comment by mpu-creare** [comment]
Cool. It's happening.
