### ISSUE TITLE
Replace `hash` property with __hash__ magic method

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#159]
**Description**
Nodes and Coordinates have a `hash` property that returns the hash of its JSON definition. We should use the __hash__ method instead. Note that it is best practice to also defined the __eq__ method (see #148) so that `a == b` implies `hash(a) == hash(b)`. This is a quick tweak.

**Sample Code**
```
# current
node.hash
coordinates.hash

# desired
hash(node)
hash(coordinates)
```

**Related**
It may likewise make sense to replace the Coordinates `copy` method with the `__copy__` method instead.

**Comment by drc-creare** [comment]
Thumbs up! I like this idea. 

Worth noting there could be some side effects. I imagine a lot of things depend on the magic __hash__ function, so we could have unanticipated effects. For example, python sets might utilize them (along with __eq__) so it could be that adding two node objects with the same pipeline definition to a set means that you end up with just one of them stored. This particular example seems fine to me though.

**Comment by jmilloy** [comment]
The __hash__ method can't replace the hash property because it must return and int, and we are using a string (md5 hexdigest). I don't think we have any reason to implement __hash__.
