### ISSUE TITLE
Integrate timing / execution information into PODPAC Lambda node

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#171]
**Description**
We need to have a sense of how much money an evaluation will cost. 
Need to also be able to set up a budget limitation easily.

**Comment by dsully1992** [comment]
This, #184 and #209 are all related.

**Comment by mlshapiro** [comment]
we have set up budgeting. I think this is sufficient, since its almost impossible to estimate how long a calculation will take.
