### ISSUE TITLE
S3 Cache Store implementation

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#181]
Implement S3 Cache store.

**Comment by drc-creare** [comment]
Note: [This](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html) describes how boto3 handles AWS credentials we should try to mimic as much of this functionality as possible:

- fall back on the aws cli credentials file(s)
- allow for overriding keys (note the addiitonal session key)
- allow for the roles that can be defined with aws cli
