### ISSUE TITLE
Implement Budgeting Reporting and Documentation for AWS Usage

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#184]
* [x] Write a function to report the cost of using Lambda functions
* [x] Add documentation that links to AWS tools for managing AWS budget. 
* [x] Automate creation of lambda functions from PODPAC.

**Comment by dsully1992** [comment]
Note: (tools/example)[https://www.concurrencylabs.com/blog/aws-lambda-cost-optimization-tools/]

**Comment by dsully1992** [comment]
There is also an AWS CLI API for creating and managing budgets, which we could wrap, or link users to.

**Comment by dsully1992** [comment]
@mpu-creare I had mentioned discussing our options a bit further, but I no longer think we need to. I plan to move forward with the plan you describe in this issue. The PODPAC aws_lambda manager will have an option to report some CloudWatch budgeting status information before evaluation, and will report the cost of a node evaluation once complete. Our AWS documentation is now slightly out of date, so I'll also update that in the process of adding budgeting information. I am convinced this is our best option, compared to more intensive wrapping of, for example, the AWS budget CLI.

**Comment by dsully1992** [comment]
Let's start by reevaluating our options. We should consider leveraging the power of AWS's budgeting tools, which would actually prevent charges outside of certain constraints. We could document this, or create some tool/wrapper in PODPAC to manage those settings.

- [ ]  (DSullivan) Make a PowerPoint describing AWS budgeting options
  - Note: these options span basic cost reporting all the way to actual spending constraints.

**Comment by mlshapiro** [comment]
Completed in v1.3.  Unfortunately there is no way to do this fully from boto3, so the user is prompted with a statement to enable cost allocation tags. This is a one-time requirement, so its not too onerous. Otherwise works as expected
