### ISSUE TITLE
What are Node `node_defaults` for, and why is _first_init private?

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#188]
I routinely have to use `_first_init`. Why is it private? It's also not well-documented.

Normally I would just use `__init__`. I guess I can't because of node_defaults. But are `node_defaults` used anywhere? What would they do, anyways, that a trait definition `default_value` doesn't do?

**Comment by mpu-creare** [comment]
You are correct. I thought I had removed `node_defaults` after the traitlets refactor... I don't quite remember all the details, I'll have to look it up.

**Comment by mpu-creare** [comment]
I need to look at this more carefully. We should discuss.

**Comment by mpu-creare** [comment]
Yes, let's get rid of `node_defaults`. I was using it for creating a pipeline factory, but I think a function would actually be more appropriate to do this. (It was used in the GeoWATCH project).
