### ISSUE TITLE
Where do I set the cache_type

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#189]
**Description**
I just got an exception that says `Trying to cache data but no cache_ctrl available. Specify cache_type.` but  I don't know how or where to do that.

Also, it prevents the code from running. It seems to me that it should work even if the cache hasn't been set up.

**Describe the solution you'd like**

~Can you put instructions for where or how into the exception? Git is a good example of this.~

I guess I just think that the exception should say `specify 'cache_type' when creating the node`.

For the second item, can we have a "no caching" cache_type, and can it be the default? Or, my preference would be for cache_type=None to be the default, and for that to do no caching but print a warning.

~Git is a good example because you can't commit without your name and email address conifgured, but when you try and it fails, it tells you how to configure *and* you can do that on the command line right wheer you are. I think we could fail when the cache is unconfigured if you could run `podpac-config cache_type='ram'` and then get back to business.~

**Comment by jmilloy** [comment]
@mpu-creare What do you think about the podpac-config script? It's out of scope of this issue, specifically.

I guess any time, or at least the first time, you *have* do something with settings it would be great if it was very easy to figure out what to do (and also easy to do). Then again, I'm behind as far as settings go, and this is the first time I've run into it. Maybe I just need to be caught up...? Does something happen automatically now when you run setup.py or anything like that?

**Comment by jmilloy** [comment]
Oh. I have to backtrack a little bit. It's a Node property, so this isn't something that a user should encounter if the node they are using has been setup correctly.

Why the heck is it a node property?

**Comment by jmilloy** [comment]
Another thought I had was that I think we should have a goal that nodes fail during *initialization* instead of during *evaluation*. If you have a long running node and then it eventually poops out because you didn't specify a cache for another node in the pipeline... Maybe it would be better if there was a way to raise the exception during initialization. Maybe a `NodeCacheCtrl` mixin that has the cache_crtl and cache_type and caching methods and that is required if you decide to add caching to a specific Node, and which checks that the cache_ctrl is valid at initialization?

**Comment by mpu-creare** [comment]
Can you post a specific code snippet of what you were trying to do? The caching interface is not mature yet, and I'm aware of some issues. I made a few choices for my recent demos that I'm not entirely pleased with...

**Comment by jmilloy** [comment]
I'm using in the [GFSSource Node](https://github.com/creare-com/podpac/blob/dbfa91bf81fd7146cd143efa17a58d738d9d1eb4/podpac/datalib/gfs.py).

The following will gave me `NodeException: Trying to cache data but no cache_ctrl available. Specify cache_type.`

```
node = GFSSource(product='SOIM', level="0-10 m DPTH", date="20181206", hour="0600", forecast"003")
node.execute(node.native_coordinates)
```

The following works:

```
node = GFSSource(product='SOIM', level="0-10 m DPTH", date="20181206", hour="0600", forecast"003", cache_type='disk')
node.execute(node.native_coordinates)
```

I would expect the node initialization in the first example to raise the standard kind of exception for when you call a function without a required parameter, something like `TypeError: GFSSource node requires 'cache_type' or 'cache_ctrl' parameter`. If the error is going to happen during evaluation, it should at least say something like`ValueError: GFSSource 'cache_type' cannot be None`, so that it's clear where the problem is.

But *really*, I would expect the node to evaluate without any cache_type specified. If the cache_type is None, it should just use no cache: `put_cache` should do nothing, `has_cache` should always return `False`, and `get_cache` should raise an exception. If caching is especially important for a particular Node, then it should leave a warning message, or in extreme cases raise its own exception.

But *really* really, I don't think that specifying the `cache_type` every time you create a node is the correct solution. The cache is an optimization that you should be able to freely turn on and off, through settings. I would expect to be able to turn on RAM caching and specify a max RAM usage; turn on disk caching and specify a cache path and max disk usage, turn on S3 caching and specify a bucket, etc, and the cache control should decide where to cache what without my involvement. And I would expect nodes to evaluate regardless what the cache settings are, whether none of the cache locations were enabled, or all of them, or any combination.

**Comment by jmilloy** [comment]
Okay, I see. I should write my node with `put_cache(..., raise_no_cache_exception=False)`. I guess I think that the default should be False. But I think I understand why you want the default to be True. If the default is True, the exception text is a tad tricky; the solution for a user just evaluating a node would be to specify the cache_type when creating the node, but the solution for a user writing their own known could be to set raise_no_cache_exception=False, and it would be great if we could cover both cases.

**Comment by mpu-creare** [comment]
> Another thought I had was that I think we should have a goal that nodes fail during initialization instead of during evaluation

That would be a great goal, but I'd like to slightly modify. How about fail *early* in evaluation. The way we work with these nodes is that we might be incrementally setting them up, so they may not be valid during initialization, but by evaluation they certainly should be. I agree about your statement for log-running nodes, that would be terrible.

**Comment by jmilloy** [comment]
@mpu-creare I'm not sure what the resolution for this is. I started it as a question because I was getting an exception and honestly had no idea what I was supposed to do, but I eventually figured it out. I don't like how the node caching defaults are set up and I think the exceptions aren't really helpful, but if I'm the only one, then I guess we should just close this and add a new (actionable) issue if it comes up again.

**Comment by mpu-creare** [comment]
I want to have a conversation with you about this... that's why it's not closed yet. I tried to put sane, safe defaults, which requires more work on the node developer's part... but if you found it confusion then:  defaults should either be changed, error messages improved, documentation improved, etc... but I think we discuss at some point.
