### ISSUE TITLE
FEATURE: Create a webpage for the project

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#19]
Should have auto-generated reference docs from docstrings as well as more user-friendly documentation for users, developers, and advocates

**Comment by mlshapiro** [comment]
docs are being served: https://creare-com.github.io/podpac-docs/

need to auto generate using gist here: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by mlshapiro** [comment]
todo:

- [ ] automate build on commit using travis
- [ ] implement and demo numpy autodoc
- [ ] tighten up current documentation copy
- [ ] add branding

**Comment by mlshapiro** [comment]
- numpy reference: https://github.com/numpy/numpy/blob/master/doc/source
- xarray reference: https://github.com/pydata/xarray/tree/master/doc
