### ISSUE TITLE
Compositor time-interpolation

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#195]
**Description**

The Compositor needs to do time interpolation.

For example, the GFS source data is whole-world data for a specific times at 3-hour resolution. A GFS Compositor would be able to interpolate to any time. Note in particular that the sources may or may not all share the same coordinates.

**Describe the solution you'd like**

To be determined.

**Comment by mlshapiro** [comment]
this relates to https://github.com/creare-com/podpac/pull/187#discussion_r240452981

At this point I think we have enough experience to spec out what the "Compositor" should be (a composite of DataSource, but perhaps DataSource should be more scalable).  Lets wrap this into a discussion starting when we do the 0.3 push.

**Comment by jmilloy** [comment]
This will be facilitated by a compositor refactor #360.

**Comment by jmilloy** [comment]
Note that the SMAPDate compositor has to specify a time tolerance in order to prevent each source from interpolating to all of the times before they can be composited. That may be able to be removed once the compositor is able to composite non-interpolated sources and then interpolate on its own. It's not yet clear to me if this can be done in a single general `DimensionCompositor` or if a specific `TimeCompositor` will be cleaner and easier to use.

**Comment by jmilloy** [comment]
See #384
