### ISSUE TITLE
Every node needs a default cache_ctrl based on the local settings

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#205]
Right now cache_type has to be specified for each node individually. By default, each node should at least have a RAM control, and anything in addition based on the settings. 

So basically: 
* Default is RAM if nothing else is specified
* Default it based on settings files
* Default is modified by nodes based on what developer has implemented
* Node cache is modified by user upon node creation.

**Comment by drc-creare** [comment]
This makes sense. Thanks @mpu-creare . 

We do not yet have a RAM cache store. Should we try to add this to 0.3.0 Release? 

Alternatively, we could could have the default cache_ctrl be no cache store. It seems to me that it would be reasonable to expect the cache_ctrl to "function" when initialized with an empty list of cache_stores. I think that's the way it is written.

**Comment by mpu-creare** [comment]
Note, this requires a ram store to be implemented. @drc-creare  please review what @jmilloy does. 

Note, this doesn't have to be the final implementation.

**Comment by drc-creare** [comment]
@jmilloy It might make sense for you to use the `feature/cache-s3-0.2.2` branch as a starting point. I've done a little reorganization and the documentation is a little better. I can also merge it into develop. Its basically complete. I plan on reorganizing (see issue #214), but after this feature branch is finished.

**Comment by jmilloy** [comment]
@drc-creare 

Okay. I literally just finished implementing a quick ram cache and am about to test. Maybe I'll jump over to the branch for that, too.

**Comment by jmilloy** [comment]
@mpu-creare Should the user be able to completely disable a cache store type in the settings?

**Comment by mpu-creare** [comment]
Yes -- with the caveat that this may potentially break certain nodes.

**Comment by jmilloy** [comment]
So each cache type has three potential states in the settings:

 * enabled, and nodes use this cache for outputs by default
 * enabled, but nodes don't use this cache for outputs by default
 * disabled

Does that sound right? We'll need settings for

 * RAM_CACHE: 'always', 'enabled', or 'disabled'
 * DISK_CACHE: 'always', 'enabled', or 'disabled'
 * S3_CACHE: 'always', 'enabled', or 'disabled'

Or would you prefer something like

 * RAM_CACHE_ENABLED: True or False
 * DISK_CACHE_ENABLED: True or False
 * S3_CACHE_ENABLED: True or False
 * CACHE_OUTPUTS_TO_DISK: True or False
 * CACHE_OUTPUTS_TO_S3: True or False
 * (and maybe CACHE_OUTPUTS_TO_RAM wouldn't be a setting because it is always True)

**Comment by mpu-creare** [comment]
How about a cache type is either enabled or disabled, and then you pick which one is the default?  
* RAM_CACHE_ENABLED: True or False
* DISK_CACHE_ENABLED: True or False
* S3_CACHE_ENABLED: True or False
* DEFAULT_CACHE: 'none', 'RAM', 'DISK', or 'S3'
* CACHE_OUTPUTS_TO: []  (where list items can include, "RAM", "DISK", or "S3")

**Comment by jmilloy** [comment]
I don't totally follow. I guess we'll need to have another conversation about this when I get back.

**Comment by jmilloy** [comment]
We discussed

 * the `DEFAULT_CACHE` setting defines a default CacheCtrl object from a list of cache stores
     - For now that can just be a list of strings, e.g. `['ram', 'disk']`, but we may sometime need to be able to define a cache store item more completely, e.g. `{'s3', 'bucket': 'MY BUCKET', ...}` instead of just `s3`.
     - The default is `['ram']`
 * The `CACHE_ALL_OUTPUTS` setting is a boolean that caches all outputs to all cache stores in the default CacheCtr.

Nodes will use the default CacheCtrl from the settings if none is provided, so nodes can override the default CacheCtrl with specific cache stores if necessary.

**Comment by jmilloy** [comment]
@mpu-creare Can you clarify `CACHE_ALL_OUTPUTS`? My understanding is that you want sort of a debugging flag that caches outputs to the default cache stores in addition to the node cache_ctrl. How do the `CACHE_ALL_OUTPUTS` setting and the node `cache_output` attribute interrelate?

If cache_output is True and CACHE_ALL_OUTPUTS is False, we should use the node cache_ctrl just like we do currently. And if cache_output is False, the CACHE_ALL_OUTPUTS should have no effect, right? But if cache_output is True and CACHE_ALL_OUTPUTS is True, we should use the node cache_ctrl just like we do currently and *additionally* cache the output to the default cache stores (which will only have an effect if the node cache_ctrl has been overridden and is not just using the the defaults). Is that correct?

What if the output is in the node cache_ctrl (so we don't have to evaluate and jut get the output from that cache) and CACHE_ALL_OUTPUTS is True? Should we still make sure to cache the output to the default cache stores?

What if the output is *not* in the node cache_ctrl and CACHE_ALL_OUTPUTS is True? Should we check the default cache stores for the output before evaluating?

One version of this could be to simply add the default cache stores to every CacheCtrl when CACHE_ALL_OUTPUTS is True. Or am I totally off the mark? That would apply to any usage of the cache, though, not just outputs.

A whole different meaning for CACHE_ALL_OUTPUTS would be that it overrides the `cache_output` setting. That doesn't seem useful to me, but is *that* what you mean?

**Comment by mpu-creare** [comment]
* `cache_output` should override `CACHE_ALL_OUTPUTS`
* `cache_output` should have 3 values:
    * True: Cache's the node's output, ignore `CACHE_ALL_OUTPUTS`
    * False: Doesn't cache the node's output, ignore `CACHE_ALL_OUTPUTS`
    * None: Follows whatever `CACHE_ALL_OUTPUTS` is set to. 

So, the default in the base `Node` should be `None`.

The `cache_ctrl` should not interact with this setting, and should be controlled separately through a similar mechanism.

Practically, that means: If `CACHE_ALL_OUTPUTS` is true, and there is no default cache stores, then a node without a prescribed cache store will NOT be cached. 

So, perhaps we should call the settings `CACHE_OUTPUTS_DEFAULT`, so that it doesn't imply that all outputs will be cached?

**Comment by jmilloy** [comment]
Ahh. Now that makes sense, *and* is easy to implement. And easy to document.
