### ISSUE TITLE
AWS Manager and Pipeline nodes should communicate exceptions/error messages.

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#209]
**Description**
Pipeline Nodes should be able to pass error messages from Lambda functions down to the user

**Describe the solution you'd like**
When I execute a lambda manager node, if an exception occurs on the lambda function, then the local lambda manager node should report the same error.

**Comment by dsully1992** [comment]
We just want an easier way to view logs from our AWS Lambda functions.

**Comment by mlshapiro** [comment]
@mpu-creare this should be handled in L1374 of aws.py

You will only get a stack trace when invoked via python
