### ISSUE TITLE
FileCacheStore.rem() does not handle `key`/`coordinates` wildcards correctly

### ISSUE THREAD

**Issue by drc-creare** [creare-com/podpac#212]
**Description**
I believe that `podpac.core.cache.FileCacheStore.rem()` will fail for some very rare cases that multiple cache entries hash to the same filename and the rem() is called with key/coordinates wildcards.

**Comment by mpu-creare** [comment]
WE talked about this and because the keys are no longer hashed, this shouldn't be an issue.
