### ISSUE TITLE
podpac should use the correct directories for settings, cache, etc by default.

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#223]
The [xdg spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines environmental variables and defaults for application files. For example

 * the correct location for podpac settings is ~/.config/podpac/settings.py, or if $XDG_CONFIG_HOME is set, $XDG_CONFIG_HOME/podpac/settings.py
 * the correct location for the disk cache is ~/.config/podpac, or if $XDG_CACHE_HOME is set, $XDG_CACHE_HOME/podpac.

See a [recent article](https://0x46.net/thoughts/2019/02/01/dotfile-madness/) for some explanation, further details, and general ranting related to this issue. I believe the current behavior creates a `.podpac` folder in the user home directory, which is exactly the anti-pattern discussed in the article.

**Comment by mpu-creare** [comment]
Nice! Thanks, good find. I agree we should fix this.

**Comment by mpu-creare** [comment]
see #393
