### ISSUE TITLE
Write an Intake Node

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#224]
**Description**
Write a datasource node that leverages intake recipes. e.g. pangeo.io/catalog.html 

**Describe the solution you'd like**
It would be nice to have a PODPAC node that can take advantage of intake recipes. If the recipe truly loads data into an xarray, then we can do the reprojection/regridding if needed. 

**Sample Code**
```python
intake_node = podpac.data.Intake(catalog=<url>, dataset=<dataset-name-from-catalog>)
...
```

**Comment by mlshapiro** [comment]
draft in #255
