### ISSUE TITLE
PODPAC Web API / Viewer

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#236]
**Description**
I want to be able to give a live demo of creating a pipeline and view the results in a webbrowser, where the tiles are generated via lambda functions on-demand and in parallel. 

This would require an API to a lambda function, and a way to view / interpret the data. 

A nice demo would be to reproduce the elements of the attached study. 

[ChewSmall2018.pdf](https://github.com/creare-com/podpac/files/3068731/ChewSmall2018.pdf)

Data available at: https://podaac.jpl.nasa.gov/CYGNSS 

More links: 
http://geoawesomeness.com/micro-sats-are-unexpectedly-trumping-landsat-sentinel-at-flood-detection/
https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2018GL077905

**Comment by mlshapiro** [comment]
this will rely on a good serialization method for UnitDataArrays (and returns from lambda functions). 

I have a few ideas on this and will take this one.

**Comment by mpu-creare** [comment]
We're going to need this for the Drought Monitoring application

**Comment by mlshapiro** [comment]
This is a really nice goal, but will not be done by 2.0

**Comment by jmilloy** [comment]
@mpu-creare Just doing some cleanup. I feel like between David's work and/or maybe Robbie's we might have this covered? Are you still wanting a version that is published as part of the podpac repo, or accessible publically from podpac.org or something like that?

**Comment by mpu-creare** [comment]
Yeah, we've gone to a different direction on this one. I think we can close it. 

Also, I'm planning a bit of a repo-split. I want to move everything in podpac/dist to another repo... then we can include the server/api stuff in there if we choose to open source it.
