### ISSUE TITLE
Implement or replace Coordinates units

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#244]
**Description**
The coordinates `units` are not integrated with the crs transform (otherwise used) and may be the incorrect type. The `crs` contains the lat-lon units and *may* also contain the altitude (`vunits`). The `units` provides a way to specify the altitude units separately from the crs.

Currently `units` is a podpac `Units` object defined on each of the underlying coordinates. I don't think this adequately serves our needs. We do not need units for time, lat, or lon coordinates; we only need units for alt at the moment. These units need to match (or not contradict) the crs and need to be integrated into the transform method.

*Describe the solution you'd like**

I propose an `alt_units` trait defined on the `Coordinates` object. It should be a string that is compatible with proj4 vunits (or it can be None). If the crs contains a complete proj4 string with vunits, the `alt_units` should match (or be None). The transform method `alt_units` argument will correspond clearly with the Coordinates `alt_units` trait. The current `units` trait defined on all underlying coordinates would be removed.

**Additional notes**

 * We can add additional units for additional dimensions when and if they are added in the future.
 * The `distance_units` argument to `Coordinates` and `StackedCoordinates` should be removed regardless, as lat and lon units seem to be handled in the crs.

**Comment by jmilloy** [comment]
@mlshapiro @mpu-creare I thought we might discuss this Monday, but I believe I will be out. This is a fairly straightforward enhancement that I believe I could implement for 1.0.0, though I would maybe leave the integration with `transform` to Marc.

**Comment by mpu-creare** [comment]
As a note, I'm using `pint` for the units in the `UnitsDataArray`. I'd prefer to use `pint` everywhere for consistency sake... but I'm also ok with a string here. `pint` does have some nice features to go from a `pint.Unit` object to a string and vice versa. 

`pint` requires that you use a universal `unit registry`, which I have setup as `podpac.units` (which I believe points to `podpac.core.units.ureg`).  I.e. don't register a new registry... because `meters` from two different unit registries will not be considered the same (as an example).

**Comment by jmilloy** [comment]
I realize now how lightweight the `Units` trait is. I'm willing to use `pint` if there is a reason. Do we need to support any non proj4-compatible altitude units? If not, we won't be doing any conversions where pint will help, and we would just be converting to `pint.Unit` and back for no reason (and the registry wouldn't matter). But if so, then I will use pint, use proj4 when possible and fallback on pint conversion when necessary.

Should this be in 1.0.0? I believe I can do either version above by Friday, but of course the proj4-only version is easier.

**Comment by mpu-creare** [comment]
Hmmm... again, difficult to answer without a use-case. 

The problem with altitude units is that researchers sometimes use units of 'pressure' which don't correspond to 'distance above ground'... so it would be nice to use pint's automatic conversion between different pressure units (atm, bar, kpa, etc.) which is not covered by Proj.4 units https://proj4.org/operations/conversions/unitconvert.html#distance-units . Although, it could be covered by the optional 'conversion_factor'... although this is probably a very rare use-case and I'm happy to let that go for 1.0

I'm primarily concerned about consistency. I don't want two user-interfaces for units in PODPAC. 

We could make the decision to use strings exclusively from the user-interface side for units, in which case I'm fine just using strings + proj4 on the altitude units side for now, and then strings on the UnitsDataArray side internally leveraging pint... what do you think?

**Comment by mpu-creare** [comment]
And yes, this would be great to have in 1.0 because I'd have a hard time justifying time on this feature in the future.

**Comment by jmilloy** [comment]
Yes, let's use a string. UnitsDataArray already uses strings and then uses pint internally. For the Coordinates altitude unit, we will use strings as well and then use proj4 internally. The `Units` trait will be removed.

If we have a use-case come up for altitude that requires non proj4 units, we can continue to use strings and then proj4 *and* pint internally as appropriate. Or, we can add a 'pressure' dimension and corresponding 'pressure_units' string which will likely use pint internally.

**Comment by jmilloy** [comment]
`UnitsNode` is not used for anything. Let me know if it can be removed. Makes sense to do it now. Otherwise, I will leave it, and I have enough info to complete this issue this week. Thanks.

**Comment by mpu-creare** [comment]
I'm fine removing `UnitsNode`. 

Well, `UnitsDataArray` uses pint.units in the 'unit' attr -- so these cannot be strings. It will do a conversion from strings to pint on creation (and vice versa on serialization), but in general if you set UnitsDataArray.attrs['units'] = str, it will break parts of the code. If you set Node.units = str, then I think everything works out fine... which I suppose is our primary use-case. 

Just something to look out for...

But in general, we're in agreement. Users will use strings to define units everywhere in the code starting at 1.0

**Comment by jmilloy** [comment]
Ah, I see. But, no, `Node(units='meters')` doesn't work currently. It gives a TraitError. But that will change.

Should the Node `units` trait be tagged as an `attr`? It's used or tested or documented anywhere so I'm having a hard time. (I wish I could be more independent and decisive here, sorry)

Something like this?

```
class Node:
    units = tl.Unicode(default_value=None, allow_none=True).tag('attr'=True)
    @tl.validate('units')
    def _validate_units(self, d):
        ureg.Unit(d['value']) # will throw an exception if this is not a valid pint Unit
        return d['value']
    ...
    def create_output_array(self, coords, data=np.nan, **kwargs):
        attrs = {'layer_style': self.style, 'units': ureg.Units(self.units)}
        return create_data_array(coords, data=data, dtype=self.dtype, attrs=attrs, **kwargs)
```

**Comment by jmilloy** [comment]
@mlshapiro @mpu-creare What do you guys know about WGS84 altitude units?

With EPSG:2193, for example, the vunits work as expected:

```
>>> crs = pyproj.CRS('EPSG:2193').to_proj4()
'+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +units=m +no_defs +type=crs'
>>> pyproj.CRS(crs + ' +vunits=ft').to_proj4()
'+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +units=m +vunits=ft +no_defs +type=crs'
```

But with WGS84, vunits are ignored:

```
>>> crs = pyproj.CRS('EPSG:4326').to_proj4()
>>> crs
'+proj=longlat +datum=WGS84 +no_defs +type=crs'
>>> pyproj.CRS(crs + ' +vunits=ft').to_proj4()
'+proj=longlat +datum=WGS84 +no_defs +type=crs'
```

That makes it impossible to transform alt units using proj4 when using WGS84, which we use by default. I already put a warning in when using WGS84 and specifying alt_units, and maybe that is enough.

This shows the warning and the ignored transform:

```
>>> c = podpac.Coordinates([[1, 2, 3]], dims=['alt'], alt_units='ft')
/home/jmilloy/Pipeline/podpac/podpac/core/coordinates/coordinates.py:198: UserWarning: alt_units ignored (crs 'EPSG:4326' does not support separate vunits)
  warnings.warn("alt_units ignored (crs '%s' does not support separate vunits)" % self.crs)
>>> c.transform(alt_units='m')['alt'].coordinates
array([1., 2., 3.])
```

Whereas if you specify a different crs, the transform works:

```
>>> c = podpac.Coordinates([[1, 2, 3]], crs='EPSG:2193', dims=['alt'], alt_units='ft')
>>> c.transform(alt_units='m')['alt'].coordinates
array([0.3048, 0.6096, 0.9144])
```

**Comment by jmilloy** [comment]
Okay, I think I get it now, and I'm more confident that the above is the correct behavior.
