### ISSUE TITLE
disk store tests break other tests

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#248]
**Description**
Something about the unit tests for the disk cache store is breaking other tests by changing the settings.

**Steps to Reproduce**

When I run the full suite of tests, the WCS `test_get_data` test fails because `settings['DISK_CACHE_DIR`] is None. If I run `test_types.py` alone, it passes, or if I comment out `test_disk_store.py`, then the rest of the tests all pass.

** Observed Behavior**

```
podpac/core/data/test/test_types.py::TestWCS::test_get_data FAILED                                                        [ 77%]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> captured stdout >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
could not broadcast input array from shape (3,718,791) into shape (24,34)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

self = <podpac.core.data.test.test_types.TestWCS object at 0x7f6662751f28>

>   ???

podpac/core/data/test/test_types.py:560: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
podpac/core/node.py:526: in wrapper
    ???
podpac/core/data/datasource.py:373: in eval
    ???
podpac/core/data/datasource.py:252: in _get_data
    ???
podpac/core/data/types.py:1027: in get_data
    ???
../env3/lib/python3.5/posixpath.py:89: in join
    genericpath._check_arg_types('join', a, *p)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

funcname = 'join', args = (None, 'wcs_temp.tiff'), hasstr = False, hasbytes = False, s = None

    def _check_arg_types(funcname, *args):
        hasstr = hasbytes = False
        for s in args:
            if isinstance(s, str):
                hasstr = True
            elif isinstance(s, bytes):
                hasbytes = True
            else:
                raise TypeError('%s() argument must be str or bytes, not %r' %
>                               (funcname, s.__class__.__name__)) from None
E               TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Additional Notes**

 * I tried to figure out where the setting is getting changed, but I can't figure it out. Maybe my diagnosis is incorrect.
 * In general, we *do* need to modify the settings for full test coverage, but they should be reset back to the original setting. I'm not sure that the cache tests are doing this, see the `make_cache_ctrl` method in test_disk_store.py for example.
 * It seems that Travis is finding other / different errors on develop than I am locally, but still related to the cache limits changes.

**Comment by drc-creare** [comment]
@jmilloy sorry, didn't see this until today and then I had to fix my podpac installation. I tracked down the bug. Working on a better fix to specifically restore the settings for these tests.
