### ISSUE TITLE
Datasource types unit tests

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#260]
The following Nodes have low test coverage.

 * [ ] PyDAP
 * [ ] Rasterio
 * [ ] H5py
 * [ ] WCS
 * [ ] S3
 * [ ] Dataset
 * [ ] Intake

**Comment by jmilloy** [comment]
Possibly the PyDAP and S3 Nodes should not count towards coverage. We can use `#pragma: co cover` for these, as in #259, if that is indeed appropriate.

@mlshapiro Feel feel of course to assign this back to me, or do the ones that you feel belong to you and then pass it along to someone else for additional work.

**Comment by mlshapiro** [comment]
of course - I will see if I can add some of these this week, but I will most likely get to it later. I need to write tests for the intake datalib too.

**Comment by jmilloy** [comment]
#348 refactored the data types and included tests.
