### ISSUE TITLE
coordinates.transform() returning dependent coordinates when not expected

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#261]
While running through the [Terrain-Tiles.ipynb](https://github.com/creare-com/podpac-examples/blob/develop/notebooks/demos/Terrain-Tiles.ipynb) I'm seeing unexpected results.

I drilled down and it is coming from the datasource coordinates transformation (Terrain Tiles comes back in EPSG:3857).  The native coordinates are a grid of UniformCoordinates1D and the requested coordinates are a grid of UniformCoordinates1D, I would expected to get back clean transformed coordinates.

**Comment by jmilloy** [comment]
I don't think it works that way, see #251

**Comment by mlshapiro** [comment]
oh wow, good catch. nice implementation too. So then something is wrong with TerrainTiles - would you mind try to evaluate that notebook? The data is empty -

**Comment by jmilloy** [comment]
Sure, I'll take a look. I wonder how the interpolator handles DependentCoordinates... may need to convert to StackedCoordinates to calculate and then reshape the results back or something.

The fact that lat and lon had to be the same size was a red flag.
