### ISSUE TITLE
Merge StackedCoordinates and DependentCoordinates

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#268]
**Description**

The DependentCoordinates are a generalization of StackedCoordinates that supports N-dimensional stacked coordinate arrays. It is confusing to have both, and also to have both the `lat_lon` and `lat,lon` dimension names.

The DependentCoordinates takes a list of numpy arrays, whereas the StackedCoordinates takes a list of Coordinates1d objects, so that needs to be sorted out as well.

Note also that ArrayCoordinatesNd is a direct generalization of ArrayCoordinates1d, so ArrayCoordinates1d should probably be removed/replaced as well.

**Proposal**

I would use ArrayCoordinatesNd directly in the DependentCoordinates (instead of a numpy array). UnformCoordinates1d would need a generalized version as well, and if we use N-dimeesional `origin`, `corner`, `step`, and `shape` traits/properties, that will correspond well with RotatedCoordinates. The clinspace spec would need to be modified, too.

And then I think we should rename DependentCoordinates to StackedCoordinates (and remove the current StackedCoordinates). 

I don't think it matters to me whether we use `lat_lon` or `lat,lon` as the dimension name.

**Comment by jmilloy** [comment]
@mlshapiro @mpu-creare We've both discussed this at some point.

**Comment by mpu-creare** [comment]
@jmilloy Is this done?

**Comment by jmilloy** [comment]
It is now! I just removed a few stray references to DependentCoordinates. I'm guessing that's why I didn't close this earlier.
