### ISSUE TITLE
Create Cloud Formation Template to Setup PODPAC AWS

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#276]
**Description**
I want to be able to set up AWS in a black-box fashion using PODPAC.

**Sample Code**
```
import podpac
podpac.cloud.deploy(username=<aws_username>, password=<aws_password>
```

**Comment by mpu-creare** [comment]
I thought I had an issue for this!

**Comment by mlshapiro** [comment]
This is complete with the `podpac.managers.aws.Lambda` node
