### ISSUE TITLE
Method/Utility to clear cache

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#286]
**Description**

We should add a small method to automatically clear the cache given the current podpac settings.

**Describe the solution you'd like**

A top level method that will clear the cache

**Sample Code**
```
from podpac.utils import clear_cache

clear_cache()  # deletes the contents of my current cache directory
```

**Comment by jmilloy** [comment]
I agree, sounds like a good thing to have in the public api.

Should be a two liner, I think

```
def clear_cache(mode=None):
    cache_ctrl = get_default_cache_control()
    cache_ctrl.clear(mode=mode)
```
