### ISSUE TITLE
Clean up Pipeline Outputs

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#287]
**Description**
I think it is strange that Pipeline nodes automatically write out output. I propose we remove this feature from pipeline nodes. I believe caching takes care of most of the functionality that this provided. 

**Describe the solution you'd like**
Instead, users can convert node outputs to whatever they like on the Python side using the node_output.to_* functions provided by `xarray`. The lamdba function handler can use the method. I propose we implement the helper function `UnitsDataArray.to_format(format)`

**Sample Code**
```
o = node.eval(coords)
nc = o.to_format('nc')  # in-memory netcdf file as BytesIO object
png = o.to_format('png')  # in-memory image file
with open('output.nc', 'wb') as fid:
    nc.seek(0)
    fid.write(nc.read())
```

**Comment by jmilloy** [comment]
I agree, I like the explicit output methods. 

1. What does a Pipeline node do, then? It sounds like we should just expose the method that parses a pipeline definition. I don't see any need to have a Pipeline as a wrapper anymore.

   ```
    s = <my definition>
    p = Pipeline(json=s)

    o1 = p.eval(<coords>)
    o2 = p.node.eval(<coords>)
    o3 = p.output.node.eval(<coords>)

    # they are all the same
    assert p.node is p.output.node
    xr.assert_equal(o1, o2)
    xr.assert_equal(o1, o3)
    ```

    Might as well cut out the pipeline:

    ```
    s = <my definition>
    node = Node.from_json(s)
    o4 = node.eval(<coords>
    ```

2. I want to caution you again from conflating caching with output. Caching *uses* some kind of output / storage mechanism, but output should not require using a cache.

**Comment by jmilloy** [comment]
I would implement the following classmethods:
 * `Node.from_definition(<dict>)`
 * `Node.from_json(<str>)` (which wraps from_definition)
 * `Node.load(<path)>` (which wraps from_json)

plus the following normal method:
 * `Node.save(<path>)`

Alternatively, we could use utility functions if you prefer:
 * `podpac.node.from_definition(<str>)`
 * `podpac.node.from_json(<str>)`
 * `podpac.node.load(<path>)`
 * `podpac.node.save(<Node>, <path>)`

and still probably provide the normal method `Node.save(<path>)`

Lastly, we could use `from_file`, but I liked the `load` / `save` pair.

Let me know what you think. It's just reorganizing existing code, so it'll be easy to implement, we just have to choose the public API structure/names.

**Comment by mpu-creare** [comment]
Interesting. One of the jobs of the pipeline node was to manage execution (i.e. for parallel jobs), but that has now been pushed on the `managers` module, of which `Lambda` is the only member. 

I agree with your proposal @jmilloy -- I think we can completely eliminate the pipelines and the class methods will serve the require purpose. It also unifies what we did for coordinates.

**Comment by mpu-creare** [comment]
It occurs to me that this would be backwards incompatible, so we'll have to bump a major version with this change...

**Comment by jmilloy** [comment]
I can implement the node classmethods without removing the Pipeline, and we can remove the Pipeline when we're actually ready to release 2.0.

**Comment by mpu-creare** [comment]
That's awesome! Great point.

**Comment by mpu-creare** [comment]
Adding a note: The `from_definition` should handle styles as well -- this should be relatively trivial since style already has the needed functionality.

**Comment by jmilloy** [comment]
* [x] Implement `Node.from_definition`, etc.
 * [x] Deprecate `Pipeline`
 * [x] Convert `Pipeline` usage to `Node.from_definition` usage in podpac.
 * [ ] Convert `Pipeline` usage to `Node.from_definition` usage in podpac-examples.
 * [ ] Node style serialization/deserialization

**Comment by jmilloy** [comment]
Let's make a new issue specifically to migrate the podpac-examples to use Node.from_definition instead of Pipelines.

**Comment by mpu-creare** [comment]
I think i've already done this while going through the notebook. :)

**Comment by jmilloy** [comment]
Oh, great! Thanks!
