### ISSUE TITLE
Cache coordinates for a datasource should depend only on the native_coordinates.dims

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#293]
**Description**
Right now if I cache a node with only lat-lon coordinates, but I use a lat-lon-time request, every new time will cache a new object. 

**Describe the solution you'd like**
For datasources, the node should be cached based on only coordinate dimensions that are a part of the native coordinates

**Sample Code**
```python
node = podpac.data.Array(
    source=np.ones((3, 4)),
    coordinates=podpac.Coordinates([range(3), range(4)], ['lat', 'lon']),
    cache_ctrl=['ram']
)
coords1 = podpac.Coordinates([range(3), range(4), '2012-05-19'], ['lat', 'lon', 'time'])
coords2 = podpac.Coordinates([range(3), range(4), '2019-09-10'], ['lat', 'lon', 'time'])
node.eval(coords1)   # Output gets cached
node._from_cache # False
node.eval(coords1) # Retrieved from cache
node._from_cache # True
node.eval(coords2)
node._from_cache # False <-- This should be True after this enhancement
```

**Comment by mpu-creare** [comment]
@drc-creare @jmilloy does this make sense to do? Any reservations?

**Comment by jmilloy** [comment]
Yes, this makes sense.

I think we could do this in the `node_eval` decorator. We already massage the coordinates there to be order agnostic by sorting the dims, so we would just also omit extra dims at that point. Not all nodes have `native_coordinates`, so I would add an additional `find_dims` method that is like `find_coordinates` but only for dims.

Another option would be to move both of these (sorting dims and removing extra dims) to *all* cache calls, not just the built-in node_eval calls. That could be implemented in the `Node` cache wrappers, for example, or deeper in the CacheCtrl methods themselves (or even deeper in the CacheStore). That would allow nodes with additional/special usage of the cache to automatically avoid these kinds of duplicate cache entries, but at the same time it would prevent them from using the cache as flexibly.

Maybe a good middle ground would be to add a `standardize_coordinates` or `standardize_dims` flag. It would default to `True` and standardize the coordinates by removing extra dims and sorting them. But it could be set to `False` to provide flexibility.

**Comment by mpu-creare** [comment]
I think it makes sense to do it in the Node? 
* If you go deeper in the cache you lose a lot of function in the node that can help with the standardization.  
* It should apply to *all* cache calls, so it doesn't belong in the wrapper

I don't think we need the flag -- once we have a use-case that needs this type of flexibility, we can implement it then. 

Do you want to take a crack at it?

**Comment by jmilloy** [comment]
Yep, no problem. I think it makes sense in the Node as well (though the node object just gets passed down into the store, so everything is still available).
