### ISSUE TITLE
Use CloudFormation to create PODPAC Lambda function

### ISSUE THREAD

**Issue by dsullivan-creare** [creare-com/podpac#298]
We may want to use CloudFormation or something like it to create PODPAC Lambda functions.

**Comment by dsullivan-creare** [comment]
This may be obsolete/duplicate of #318. I'm not positive we are going to use CloudFormation, but the same functionality ("easy button" lambda function creation) should be accomplished.

**Comment by mlshapiro** [comment]
This is complete with #318
