### ISSUE TITLE
coordinate testing

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#3]
This involves migrating some old unit tests to pytests, writing some new unit tests, and removing some old unit tests.

 * [x] util
 * [x] base_coordinates 
 * [x] coordinates1d
 * [x] array_coordinates1d
 * [x] uniform_coordinates1d
 * [x] stacked_coordinates
 * [ ] coordinates
 * [x] cfunctions
 * [ ] group coordinates

**Comment by jmilloy** [comment]
This issue should now be addressed again in earnest alongside #84.
