### ISSUE TITLE
BUG: Intake catalog example has an issue with the time

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#302]
**Description**
Running https://github.com/creare-com/podpac-examples/blob/master/notebooks/demos/intake.ipynb I see the time goes from 1950 to 2099 -- this is probably a mistake, so the time is not being parsed correctly for this example. 

@mlshapiro can you have a quick look?

**Comment by mlshapiro** [comment]
@mpu-creare this must be a demo dataset, the csv file has values through 2099 :)

This is working as expected at the current head, closing for now
