### ISSUE TITLE
ENH: Allow Nodes to return multiple channels of data

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#305]
**Description**
Right now I can't fit a time series as a beta distrubtion and return both the alpha and beta parameters. I also cannot load a hyperspectral datasource and have all the channels available. 

* Turn off the checks for the 'data' dimension on xarray outputs
* Handle any `from_xarray` calls
* any other tricky points? Where UnitsData Array is used as an input

**Comment by jmilloy** [comment]
Proposal: add a dimension to the output UnitsDataArray. Some methods that take unitsdataarray inputs (e.g. from_xarray) will need to be updated. Use Node attrs to select a subset of channels.

**Comment by jmilloy** [comment]
This is completed in #348
