### ISSUE TITLE
ENH: Whitelist pipelines for public-facing lambda functions

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#307]
**Description**
With a public facing website, you want to limit the generality of the lambda so that a nefarious grad student doesn't use your public function to do huge computations at your expense. 

**Describe the solution you'd like**
Include a `whitelist.json` file to the lambda function distribution that specifies specifically what pipelines are allowed to fun in that function. (potentially using the hash of the pipeline) 

May also limit the size of the request, but less dangerous because the lambda would just crash.

**Comment by mlshapiro** [comment]
I think we should do this in the settings file like we handle unsafe_eval_exec

**Comment by mlshapiro** [comment]
Implemented in 15398c4ab0060ccff78cc0877406c2d74423a847. See #336
