### ISSUE TITLE
Support integer DataSource.

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#31]
Currently a DataSource source must be floats for the interpolation to work. NaN values are used for missing data.

It would be nice to support integer sources with a custom (integer) no-data value.

**Comment by mlshapiro** [comment]
will address in #7

**Comment by mlshapiro** [comment]
@jmilloy interpolation as now implemented supported integer data sources, but the output data is cast to floats if the interpolation process runs.  For nearest neighbor, I think this comes from xarray in the reindex process (need to check).

Can you edit below for an example of what you want to see?

```python
>> source = np.array([1, 2, 3])
>> native_coords = Coordinates([[10, 15, 20]], dims=['lat'])
>> node = Array(source=source, native_coordinates=native_coords)
>> eval_coords = Coordinates([[11, 12, 19]], dims=['lat'])
>> node.eval(eval_coords)

array([1., 1., 3.])
```

**Comment by jmilloy** [comment]
I really don't remember writing this issue. I wonder if the nan_vals was not implemented at the time.
