### ISSUE TITLE
ENH: Add multithreading to Algorithm Node

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#312]
**Description**
We want algorithms nodes to evaluate their inputs in parallel (multi-threaded) so that we don't have to wait for latency from S3 for all nodes in serial. 

**Describe the solution you'd like**

Use an implementation similar to the Compositor nodes. Need to wait for all evaluated nodes to return before continuing with the algorithm part... 

**Additional context**
This is critical to get the Drought Monitor working quickly.

**Comment by jmilloy** [comment]
What is the fastest way I can reproduce this? I think I can implement this without using AWS, but I would prefer to test with the Drought Monitor node that is slow so I can see if I have succeeded or not.

**Comment by jmilloy** [comment]
I will consider adding a `MultithreadedNodeMixin` that factors out iteroutputs, but it may be that the requirements for Algorithms are sufficiently simpler that having an algorithm-specific method makes more sense.

**Comment by mpu-creare** [comment]
I'm taking this on as I need to have it  done and have time to work on it right now. 😄

**Comment by mpu-creare** [comment]
started here: ce8be10949856637108b1339bfc8f97e4011b62d
