### ISSUE TITLE
proj4 +init syntax is deprecated

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#316]
**Description**
I don't entirely follow this, but it appears that the `+init` syntax is deprecated.

See
 * https://github.com/pyproj4/pyproj/issues/355
 * http://pyproj4.github.io/pyproj/stable/gotchas.html#init-auth-auth-code-should-be-replaced-with-auth-auth-code

**Steps to Reproduce**

The coordinates tests `test_crs`, `test_alt_units`, and `test_ne_hash_alt_units` use the `+init` syntax, for example:

```
c = Coordinates([0, 1], dims=['lat', 'lon'], crs="+init=epsg:2193")
```

**Observed Behavior**

This will emit a DeprecationWarning depending on your version of pyproj (e.g. pyproj 2.4.0) and your warnings filters.

**Expected Behavior**

We should not depend on deprecated features, if possible.

**Additional Notes**

In the case of `"+init=epsg:2193"`, this is easily replaced with "epsg:2193"`. However, I'm not sure what the solution is for "+init=EPSG:2193 +vunits=ft". Can we simply drop support for that syntax (or for +vunits altogether)? Maybe this is just a matter of avoiding `+init` in our tests and letting the DeprecationWarning get to the user if they use it.

**Comment by jmilloy** [comment]
In the meantime, I'm going to add a filter for this warning in our tests.

**Comment by mlshapiro** [comment]
this looks as simple as removing "+init" from the prefix in our examples. I will update and require pyproj > 2.4 in the setup and run through the examples.

**Comment by mlshapiro** [comment]
We can still use proj strings, you just can't start from a default crs in the same line (i.e. "epsg:2193 +vunits=ft"). You can now either specify a single standard code (`crs="epsg:2193`") or a single proj4 string (`crs="+proj=merc +vunits=ft"`).

Note it sounds like proj4 strings can be loss-y, so internally we probably want to start using `wkt2` (`pyproj.CRS.to_wkt()`)  when we are making string manipulations. It seems like the community is still warming up to proj v6, where this deprecation happened, but luckily we don't handle much of this on our end. We pass the `crs` right on the pyproj, who handling working with it.  Its only the vunits handling, which seems ok for now.
