### ISSUE TITLE
AWS Lamda update documentation to create PODPAC lambda function

### ISSUE THREAD

**Issue by dsullivan-creare** [creare-com/podpac#319]
For example, include documentation on installation of docker. This will be impacted by #318

**Comment by mlshapiro** [comment]
This is primarily documented in https://github.com/creare-com/podpac/blob/master/dist/aws/README.md and https://github.com/creare-com/podpac/blob/master/dist/aws/build_lambda.sh.

More instructions (and details) to come in https://github.com/creare-com/podpac/blob/master/doc/source/aws-development.md
