### ISSUE TITLE
doc improvements

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#32]
General issue to support doc improvements leading to 0.1.0

- [ ]  support viewing multiple versions of documentation
  - View multiple versions of podpac docs on the built documentation website via a dropdown selection. This is a built in feature of read the docs. Ideally this would be a sphinx based solution
- [ ] include code coverage in documentation

**Comment by mlshapiro** [comment]
@mpu-creare I don't think we need to support multiple versions of the docs right now. if you disagree i will leave this up, otherwise lets remove this for now

**Comment by mpu-creare** [comment]
Agreed closing until we want multiple version.
