### ISSUE TITLE
BUG?: ModuleNotFoundError: No module named 'pre_commit'

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#322]
**Description**

My local development environment was out of date for my branch, so I ran `pip install -e .[devall]`. I encountered the following error:

```bash
Installing collected packages: podpac
  Found existing installation: podpac 1.1.0+62.gdf5fd6
    Uninstalling podpac-1.1.0+62.gdf5fd6:
      Successfully uninstalled podpac-1.1.0+62.gdf5fd6
  Running setup.py develop for podpac
    ERROR: Command errored out with exit status 1:
     command: /anaconda3/envs/podpac/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/marcus/computing/creare/podpac/podpac/setup.py'"'"'; __file__='"'"'/Users/marcus/computing/creare/podpac/podpac/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/marcus/computing/creare/podpac/podpac/
    Complete output (22 lines):
    running develop
    Traceback (most recent call last):
      File "/anaconda3/envs/podpac/bin/pre-commit", line 7, in <module>
        from pre_commit.main import main
    ModuleNotFoundError: No module named 'pre_commit'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/marcus/computing/creare/podpac/podpac/setup.py", line 138, in <module>
        long_description_content_type="text/markdown"
      File "/private/var/folders/pz/vvy26vqd35b84xw_tvz62r9r0000gn/T/pip-build-env-tyoc8q2k/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/anaconda3/envs/podpac/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/anaconda3/envs/podpac/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/anaconda3/envs/podpac/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/marcus/computing/creare/podpac/podpac/setup.py", line 107, in run
        subprocess.check_call(["pre-commit", "install"])
      File "/anaconda3/envs/podpac/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['pre-commit', 'install']' returned non-zero exit status 1.
    ----------------------------------------
  Rolling back uninstall of podpac
  Moving to /anaconda3/envs/podpac/lib/python3.7/site-packages/podpac.egg-link
   from /private/var/folders/pz/vvy26vqd35b84xw_tvz62r9r0000gn/T/pip-uninstall-kkv9qzn1/podpac.egg-link
ERROR: Command errored out with exit status 1: /anaconda3/envs/podpac/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/marcus/computing/creare/podpac/podpac/setup.py'"'"'; __file__='"'"'/Users/marcus/computing/creare/podpac/podpac/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

The notable piece is:

```
    running develop
    Traceback (most recent call last):
      File "/anaconda3/envs/podpac/bin/pre-commit", line 7, in <module>
        from pre_commit.main import main
    ModuleNotFoundError: No module named 'pre_commit'
```

I have `pre-commit` installed and checked a few things (confirmed environment, etc), but I can't seem to figure out whats going on.

For now, I commented out the section of `setup.py` that installs the precommit:

```python
# install pre-commit hooks after setup in develop mode
class PostDevelopCommand(develop):
    def run(self):
        try:
            subprocess.check_call(["pre-commit", "install"])
        except subprocess.CalledProcessError as e:
            print("Failed to install pre-commit hook")
            
        develop.run(self)
```

**Steps to Reproduce**

Not exactly sure...

**Expected Behavior**

I would expect the pre-commit hook to not break the development install process

**Additional Notes**

This may not be a bug - it may be specific to my environment or anaconda, but I just wanted to document it in case it came up again.

**Comment by mpu-creare** [comment]
I had the same problem on ubuntu on my home computer recently. I did a little debugging and didn't get anywhere. When I do `pre-commit install` from the commandline it works fine, but `subprocess.check_call` doesn't seem to work.

**Comment by mlshapiro** [comment]
great i'll commit my quick fix so that it doesn't stop others. If the pre-commit doesn't work its not the end of the world, though it could make merging harder. We have the python black commands so we can always pre-process branches before merging

**Comment by jmilloy** [comment]
I just created a new pip environment and ran `pip install -e .[devall]` without any problems. The `pre-commit` script runs from the command line and from `subprocess.check_call`, and I can `import pre_commit`. (It is apparently also working in our CI, right?

What is the "quick fix"? Can you put it in a `try ... except ...` instead of commenting it out, so that it still works for people without problems with their environments?

Note that our TravisCI test will fail if code is not autoformatted correctly, so that's a good fallback to ensure that the code is formatted for releases even if it isn't formatted on some commits.

**Comment by jmilloy** [comment]
@mlshapiro I notice that you are on conda. @mpu-creare Are you also? Is this something that works in venv or virtualenv environments, but maybe not conda environments?

> I have pre-commit installed and checked a few things (confirmed environment, etc), but I can't seem to figure out whats going on.

Can you `import pre_commit` in a python shell?

**Comment by mpu-creare** [comment]
I was also working in Conda at home.

**Comment by jmilloy** [comment]
Oh, sorry, it already has a try except, just needs another except case for this pre_commit import problem (or a more general except clause).
