### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#327]
Python 3.8 is out.
 - [x] setup/installation
 - [x] tests
 - [x] TravisCI

**Comment by mpu-creare** [comment]
Sure, give it a go. I was planning to do the same thing.

**Comment by jmilloy** [comment]
I just noticed that python 2.7 is no longer tested. Have we dropped support for Python 2? That would be awesome, and I would love to take a pass and clean some things up if that's the case.

**Comment by mpu-creare** [comment]
Unfortunately not. I would also love to drop support for Python 2.7, and I'm going to start making a serious case for it soon. 

Right now it's dropped because the 2.7 version of rasterio 1.x.x is segfaulting, causing the unit tests to fail. See 61714ce3a655a6647fa69bd7dbe8898157741d32

**Comment by jmilloy** [comment]
There is an issue with pyproj when using python 3.8.

See https://stackoverflow.com/questions/55084003/pyproj-package-installation-proj-dir-variable

I tried reverting to pyproj 1.9.6, which is suggested in numerous places, without success.

I moved this to the next release. Can someone more familiar with pyproj figure this out? I assigned @mlshapiro for this reason, but feel free to shoot it back to me if you want to.

**Comment by jmilloy** [comment]
3.8 is new enough that there aren't precompiled binaries for a lot of libraries. The PROJ_DIR issue comes up because pip is trying to install pyproj from source. This will work itself out before long. We'll make sure to add it before the next release.

**Comment by jmilloy** [comment]
I've added this to TravisCI, and tests are passing, but there is a problem with coveralls that still needs to be sorted out #347
