### ISSUE TITLE
Refactor Caching

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#33]
**Description**
Presently there is no clear/consistent way to cache objects to RAM/disk. In fact, core.node.Node has multiple save/load/write functions that should be unified. I suspect part of this was used for the initial caching functionality, and another part was used for the Pipeline implementation. This needs to be cleaned up. 

**Describe the solution you'd like**
Define a single consistent interface for caching, saving, and loading files.

**Comment by drc-creare** [comment]
It may be desirable for caching to be managed in a centralized store behind the scenes. It could be opportunistic based on resource constraints (limited RAM) and cost to compute. [Dask](https://dask.pydata.org/en/latest/caching.html) is incorporating something like this using [cachey](https://github.com/dask/cachey). Cachey considers compute-time, data size, and access time (e.g. how recently was the data used) to compute a score used to prioritize which objects are cached once resource limits are hit.

We may also want to introduce the concept of an "execution session" when caching data, or the values of temporary instance variables (see issue #38 ). Tensor Flow uses execution sessions to manage evaluating (e.g. executing) their computational graphs. This is useful for neural networks where you want to repeatedly execute the same computational graph for different inputs. Not sure we want to use the same exact system, but something similar could be useful. This possibly centralizes execution management (at least under the hood). Consider the case of using weather forecast data as an input. Forecasts are updated periodically, so the value for a specific region and time can actually change over time. If we incorporate the "session" in the caching mechanism (maybe just add a session id to the lookup key) we can account for stale data.

**Comment by mpu-creare** [comment]
We discussed a few aspects:
* Expiration of the cache
* Caching to ram for the initial release
* Caching to S3 for convenience
* Caching to prevent egress for NASA -- Main next step for disk caching

**Comment by mpu-creare** [comment]
When this is finally refactored, we need to remove the `source` attribute from Compositors, since this was used (as a hack) to uniquely identify the compositor. The unique identifier will now the the pipeline definition. @jmilloy  FYI

**Comment by drc-creare** [comment]
Yes, thanks @mpu-creare . That said I am using it currently as a "user friendly" identifier that goes in the filenames when its a disk store. Its not utilized by the cache to function properly. This should be changed to some other property in `Node` (instead of `Compositor`) and should have a more descriptive name.

**Comment by jmilloy** [comment]
@drc-creare sorry I don't totally follow you. Is the `source` attribute in the filename just to make them more human readable, or is it actually required to make the filenames unique?

**Comment by mpu-creare** [comment]
I followed (I think)

> Is the `source` attribute in the filename just to make them more human readable
Yes.
> or is it actually required to make the filenames unique?
No.

**Comment by drc-creare** [comment]
Yeah, just human readable. That's a better way to describe it. Its optional and not necessary for the cache to function properly. There was some desire for the cached files to be not completley obtuse, so I'm attempting to replicate the original strategy of nested folders representing classes and the option of some kind of human readable component to the filename.

**Comment by jmilloy** [comment]
I think the `base_ref` property in Node could be a good choice for this then. It's defined for all nodes and should always be a string (unlike the `source`).

**Comment by drc-creare** [comment]
Thanks @jmilloy , I will take a look at `base_ref`. It sounds like a good property to use.  

Would different instances of Node objects that have the same pipeline definition have the same `base_ref`?  

I'll have to be careful about this. Don't want different "human readable" parts of the filenames resulting in multiple files for the same pipeline_definition/key/coordinates.

**Comment by jmilloy** [comment]
Yep, I think so.

**Comment by mpu-creare** [comment]
Please add a 1GB disk cache limit. If users exceed this limit, please throw warning. Also check to see if disk space is available before caching? At least a GB
