### ISSUE TITLE
CHORE: remove create_dataarray() from units module in 2.0

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#337]
**Description**

`create_dataarray()` is deprecated in podpac 2.0 by #334. Remove references and tests when we release 2.0

**Describe the solution you'd like**

- [x] remove test in `test_units.py`
- [x] remove reference in `units.py`

**Comment by jmilloy** [comment]
@mlshapiro There is a release/2.0 branch with another deprecation removed already. I did that so that we can close out these kinds of issues.

**Comment by mlshapiro** [comment]
ah this is a super good idea.  How do you want to manage this? Should we continue to merge develop into release/2.0 as we finish features and resolve the changes?

**Comment by jmilloy** [comment]
Yeah, I think it's a good idea to merge in develop from time to time.

**Comment by mlshapiro** [comment]
@jmilloy closed in ca054c90b299c577fb36e1dd9208f1220cc72f65
