### ISSUE TITLE
ENH/BUG: Raise warning when interpolation params are ignored

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#340]
**Description**

Currently, some interpolation params will be ignored if the Interpolator doesn't support them. 

**Describe the solution you'd like**

Raise a warning if interpolation params are defined, but the interpolator being used doesn't use them.

**Additional context**

This will be dependent on keeping the Interpolators up to date with the params they support.

**Comment by jmilloy** [comment]
@mlshapiro Can you give an example of an unsupported parameter? Are these parameters that we intend to support in the future?

**Comment by jmilloy** [comment]
I think this happens when the spatial tolerance is ignored when dependent coordinates become necessary due to projection transform.

**Comment by mlshapiro** [comment]
Yes, like `spatial_tolerance` and `time_tolerance` - they are included in classes like Rasterio and ScipyGrid, but they don't do anything. And they also may be used by Rasterio only by certain interpolation methods.  

I'm not sure a warning is necessary for this scenario, but I think that some though should go into how we handle parameters/dimensions that are *ignored* when doing an interpolation.

**Comment by jmilloy** [comment]
Matt pointed out that it can be a surprise when the coordinates are converted to DependentCoordinates internally and then a different interpolation method is used which ignores your spatial tolerance.

**Comment by mpu-creare** [comment]
And now that I found the notebook again, I'll point it out here: https://github.com/creare-com/podpac-examples/blob/master/notebooks/examples/drought-monitor/03-data-access-harmonization-processing.ipynb
