### ISSUE TITLE
BUG: Compositor attribute "source" is potentially confusing

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#341]
**Description**

`OrderedCompositor(source="some random name")` - what does source mean? `sources` is the  important keyword here.

If `source` is actually critical, then we should document what this needs to be, but

**Comment by jmilloy** [comment]
I believe we should remove `source`.

It is only used in the `Compositor.__repr__`, and will almost always use the default value (which is pulled from the sources). The `__repr__` implementation should handle displaying the sources in some whay itself.

Maybe SMAP uses it, but if so, it should just create its own trait.

**Comment by mpu-creare** [comment]
Agreed.

**Comment by jmilloy** [comment]
The SMAP OrderedCompositor has a source property. I think I can just remove it from the Compositor without any other changes. Doing that real quick right now.

**Comment by jmilloy** [comment]
cfffe5d
