### ISSUE TITLE
"You will likely lose important projection information" when using using alt_units

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#346]
**Description**

The `set_vunits` coordinates utility function triggers a pyproj warning about losing information with some versions of pyproj. The Coordinates `alt_units` requires this function.

**Steps to Reproduce**

Using python 3.8 and pyproj 2.4.2:

```
from podpac.core.coordinates.utils import set_vunits
set_vunits("+proj=merc +vunits=m", "ft")
```

You can also run the tests in `test_coordinates_utils.py::test_set_vunits` and many others.

**Observed Behavior**

```
UserWarning: You will likely lose important projection information when converting to a PROJ string from another format.
```

This occurs in both locations that `set_vunits` calls `to_proj4()`.

**Expected Behavior**

The `+vunits` should be set without any warnings.

**Additional Notes**

I think the problem is that the way we handle the `alt_units` parameter uses proj4 strings internally, which are lossy. We should either, in order of preference:
 - fix `set_vunits` to avoid losing projection information, if possible
 - catch the UserWarnings in `set_vunits` and replace them with our own warning that using `alt_units` may be lossy. We should also point to an alternative.
 - remove the `alt_units` parameter. The user would have to use the `crs` string to specify altitude units.

**Comment by jmilloy** [comment]
@mlshapiro I think this is a case where the solution will be easy to implement, but choosing the correct one takes more familiarity with pyproj than I have.

I think the user will see this warning when they use `alt_units`. So in a way the problem is created because we are trying to support `alt_units` alongside `crs` strings, and the way have implemented that uses `proj4` strings, which are lossy.

In #316, you noted that we should consider using `to_wkt` internally. If that would solve the problem, then we should do that instead to fix `set_vunits`. That way we can continue to support a non-lossy `alt_units` argument for convenience.

If `alt_units` parameter is always going to be lossy, I think we should either remove it or issue our own warning. If users can still specify altitude units fully within the `crs` parameter, a convenient-but-lossy `alt_units` parameter may be counter-productive. But if we do want to keep the convenience, I think we need to issue our own warning because the pyproj warning will be not be clear to someone just trying to use our `alt_units`.

**Comment by jmilloy** [comment]
(Note: I originally marked this as fixes-and-maintenance because I thought the fix might just be in ignoring the warnings in our tests, but upon further investigation, I think it is likely an acual problem in our `alt_units` handling that we should address, so I "escalated" to a bug.)

**Comment by mlshapiro** [comment]
@jmilloy digging into this a little more. I think we should remove `alt_units`. It doesn't really fit into proj6 paradigm, and it would simplify our lives. I will create a PR

**Comment by mlshapiro** [comment]
this is a little tough since vertical units are not really (and actively stripped out) from the standard crs projections. See PR #350
