### ISSUE TITLE
coveralls is not working for python 3.5 or 3.8

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#347]
The 3.5 and 3.8 jobs on TravisCI are failing because of the following error running `coveralls`:

```
$ coveralls
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/bin/coveralls", line 7, in <module>
    from coveralls.cli import main
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/coveralls/__init__.py", line 2, in <module>
    from .api import Coveralls
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/coveralls/api.py", line 13, in <module>
    from .reporter import CoverallReporter
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/coveralls/reporter.py", line 10, in <module>
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter'
The command "coveralls" exited with 1.
```

The error is the same in the python3.8 job.

Locally, I can `from coverage.report import Reporter` just fine in both python3.5 and python3.8 environments, so I'm not sure what's going on or how to really debug it.

**Comment by bannsec** [comment]
My tests are failing with this error with Python 3.6 as well.

**Comment by mpu-creare** [comment]
Seems related to this: https://github.com/z4r/python-coveralls/issues/73

**Comment by mpu-creare** [comment]
Seems like the 3.6 env is using coverage 5.0, while the passing 3.7 env is using coverage 4.x.x

**Comment by jmilloy** [comment]
[These guys](https://github.com/SwamyDev/reinforcement/pull/7/files) pin the coverage module in the travel config

```
script
 - pip install coverage==4.5.4
 ...
```

Maybe there is something like this that we can do, or similarly maybe we can pin the coveralls version in our setup.py?

**Comment by jmilloy** [comment]
Okay, pinning coverage worked. See https://github.com/creare-com/podpac/commit/0a7ba0b0f47b2c9c1832ff5ccba5316e695f4219

**Comment by amykyta3** [comment]
Commenting here since this thread shows up in Google searches often.

There's no need to pin to an older version of coveralls.
Instead, make sure you are *not* installing `coverage` or `python-coveralls` as they seem to cause some sort of conflict  (See: [z4r/python-coveralls#73](https://github.com/z4r/python-coveralls/issues/73)).

This combination is working for me:
```
pip install -U pytest pytest-cov coveralls
```
