### ISSUE TITLE
How is Compositor.select_sources supposed to work?

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#351]
I'm working on multiple-outputs support for the Compositor, and updating the tests.

What is `select_sources` supposed to do? I can't get it to work. It seems like it should select a subset of the sources, as in only the sources with native_coordinates that intersect the requested coordinates, but that's not what it does. It looks like it is implemented to select a subset of each source, which makes some sense, but our datasources aren't indexable.

So, which of the three behaviors is correct for `select_sources`?
 1. select only the sources that intersect the requested coordinates (potentially returning an empty list, but without modifying the selected sources)
 2. subselect each source with its intersection with the requested coordinates (always returning all of the sources, but modified)
 3. both: subselect each source and also filter out sources that have an empty intersection

I think it is currently trying to do (2), while code elsewhere expects (1), and furthermore source subselection is not implemented. Is this just a bug? I can easily fix it to do (1). Otherwise, we need to add a fallback for sources that don't have subselection (that just doesn't actually subselect) and should also filter out nonintersecting sources.

**Comment by mpu-creare** [comment]
The missing piece is that you need to also supply `source_coordinates`  : " Coordinates that make each source unique. This is used for subsetting which sources to evaluate based on the
        user-requested coordinates. It is an optimization."

This functionality is used in the SMAP context where you have hundreds/thousands of folders each associated with a date, where the date makes the folder unique in terms of coordinates. So, by subselecting here, I don't have to iterate through all of these (each http get request takes time) but I can just go directly to the needed folder. This is less relevant now with the EGI interface. 

Here's an example use (presumably `Arange` only has data at time 0, and `SinCoords` at time 1):
```python
In [48]:  coords = podpac.Coordinates([podpac.clinspace(0, 1, 10), podpac.clinspace(0, 1, 11), 0], ['lat', 'lon', 'time'])

In [49]: source_coords = podpac.Coordinates([[0, 10]], ['time'])

In [50]: node = podpac.compositor.Compositor(sources=[podpac.algorithm.Arange(), podpac.algorithm.SinCoords()], source_coordinates=source_coords)

In [51]: node.select_sources(coords)
Out[51]:
array([<podpac.core.algorithm.utility.Arange object at 0x000001EF975A47B8>],
      dtype=object)

In [52]: node.select_sources(source_coords)
Out[52]:
array([<podpac.core.algorithm.utility.Arange object at 0x000001EF975A47B8>,
       <podpac.core.algorithm.utility.SinCoords object at 0x000001EF975A47F0>],
      dtype=object)
```

**Comment by jmilloy** [comment]
Okay. So `source_coordinates` should be a *single* dimension of coordinates 'time' of the *same length* as the `sources`. Is that right?

**Comment by mpu-creare** [comment]
It could be a `lat_lon_time` triplet as well, but yeah, it needs to be a 1-D coordinate the same length as the `sources`... documentation could probably be improved.

**Comment by jmilloy** [comment]
Thanks, see my PR with corrected passing tests, some validation , and a brief docstring update.

**Comment by jmilloy** [comment]
#352
