### ISSUE TITLE
Rename `native_coordinates` to `coordinates` for 2.0

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#358]
**Description**

While writing documentation I am brainstorming some interface improvements.

1. Change `native_coordinates` attribute to `coordinates`

```python
node = Rasterio(source="file.tif", coordinates=podpac.Coordinates)
node2 = Rasterio(source="file2.tif", coordinates=podpac.Coordinates)
output = node.eval(node.coordinates)
```

**Comment by jmilloy** [comment]
The verbosity doesn't bother me, but I've always thought that `native_coordinates` was confusing.

Note that the Node object does not have `native_coordinates`, so we're really talking about allowing `eval` accepting `DataSource` objects but not other types of nodes. 

I'm not in favor of eval accepting DataSource objects. I prefer the explicit `output = node.eval(node2.coordinates)`. I think accepting DataSource objects would violate at least five of the items in PEP 20.

**Comment by jmilloy** [comment]
A big one for me that could be improved and better documented is the `shared_coordinates`, `source_coordinates`, etc in the Compositor.

**Comment by mlshapiro** [comment]
> I'm not in favor of eval accepting DataSource objects. I prefer the explicit `output = node.eval(node2.coordinates)`. I think accepting DataSource objects would violate at least five of the items in PEP 20.

This made me laugh, you are right. 

> Note that the Node object does not have native_coordinates, so we're really talking about allowing eval accepting DataSource objects but not other types of nodes.

Yes i'm just talking about DataSource nodes

I think we should promote this to an improvement for 2.0 to deprecate `native_coordinates` for `coordinates`.

> I don't know if this is meant to be a catch-all for these kinds of interface changes, but a big one for me that could be improved and better documented is the shared_coordinates, source_coordinates, etc in the Compositor.

Compositor generally needs help. We can cross this bridge with whoever takes on the `Compositor` overhaul.

**Comment by mlshapiro** [comment]
I suggested this earlier, but I think `node.eval()` should by default evaluate at the `coordinates`. This is a problem for huge datasets, but individual nodes could overwrite the default behavior to raise and Exception.

**Comment by mlshapiro** [comment]
The main takeaway from this discussion is that `native_coordinates` should be renamed to `coordinates` on a Node.  @mpu-creare you can ignore the rest of the musings.

If you agree, I will close this and make an issue for implementation.

**Comment by mlshapiro** [comment]
@mpu-creare can we do the `native_coordinates` to `coordinates` move? I still think this is a good idea, but would be highly invasive, so we'd want to do it efficiently to minimize merge conflicts.

I can take the lead and push this evening, if we're in agreement. If not, I will close this issue as all other notes have been discussed.

**Comment by mpu-creare** [comment]
Let's do it!
