### ISSUE TITLE
Improved handling of computed Dataset source, Compositor sources, and other Node attrs

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#359]
**Description**

Computed attrs should not be included when serializing a node. Furthermore, including them can lead to deadlock if the computed values attempt to use the cache, and the current workarounds are quite opaque. Some examples of computed attrs are `Dataset.source` and `Compositor.sources` in SMAP and MODIS datalib; `Compositor.outputs`; and `Rasterio.nan_vals`.

**Describe the solution you'd like**

 * `Datasource.source`, `Datasource.interpolator`, `Compositor.sources`, and `Algorithm.inputs` should be `Node.attrs` like everything else, without requiring special handling.
 * Like `native_coordinates`/`get_native_coordinates()`, we should provide `get_*` machinery for `Datasource.source`, `Compositor.sources`, and other attrs that are sometimes provided explicitly and sometimes computed from other attrs.
 * These `get_*` methods should *remove* the `'attr'` tag from the traits when called, so that the corresponding traits are not inclued in the base_definition.
    - note that `base_definition` can be referenced before the `get_*` method or default has been called, so it should *also* check `trait_is_defined`. I believe this will offer the desired behaviour.
    - `@tl.default` methods may also want to remove the `'attr'` tag, because default values also do not need to be included in the definition, though in some case, it may be better to include them for generating consistent cache keys
 * In some cases, `Datasource.native_coordinates` are *not* computed should be *included* in the base_definition. These changes will make it easier to do that clearly, too.

**Comment by jmilloy** [comment]
I am unable to automatically detect if a trait is computed or not before it has been referenced.

**Describe the solution you'd like, updated**

 * When appropriate, `Datasource.source`, `Datasource.interpolator`, `Compositor.sources`, and `Algorithm.inputs` should be tagged as `attr=True` like everything else, without requiring special handling.
 * Traits tagged as `attr=True` will be included in the Node `definition`. *This means they will be included when serializing the Node, when creating a Node hash for caching, and when comparing node equality.*
 * Traits that are computed should not be tagged as `attr=True` so that they are not included in the Node `definition`. They can be cached without causing deadlock.
 * Base Nodes with commonly computed traits should provide `get_*` methods so that users can avoid using `@traitlets.default`. This also facilitates automatic caching of these traits in the base node, when desired.
 * in DEBUG mode, the `read_only` flags will be disabled, so that computed attrs can be explicitly set if necessary during node development.

Note that traits can be tagged as an attr in some Nodes but not in others. For example
 * `DataSource.native_coordinates` is usually computed, but will be tagged as an attr in the `Array` datasource.
 * `DataSource.source` is usually an attr, but in specific datalibs where it is computed, the source trait would be redefined *without* the attr tag.

@mpu-creare Is this going to be a problem as for as you know? For example, the `native_coordinates` have historically supported **both** explicit assignment at instantiation and computation using `get_native_coordinates` in every datasource, but I think any specific datasource only needs one or the other.

**Comment by mpu-creare** [comment]
I think this is a fine proposal. Only things I'd think about: 
* What happens when `get_*` is expensive to compute? We've been using `traitlets.default` as a way to cache it, and we used to have a `cached_property` decorator... so we just need  a mechanism to avoid calling an expensive `get_*` every time we need it. 
   * So wait... are you're saying that `self.native_coordinates = self.get_native_coordinates()` ?? and you don't want to set that up with something like
```python
tl.default(native_coordinates)
def default_nc(self): 
    return self.get_native_coordinates()
```
* What happens with inheritance? I want to use the rasterio base Node, but I know my source is computed instead. 
   * you probably just do a `def source(self)` in the new node....

**Comment by jmilloy** [comment]
Truthfully, if it were up to me, I would not use traitlets or the `get_*` methods at all. They make all of this much harder for developers and users, and because almost everything is read_only, we don't have any need for dynamic type checking. So I would just use a property for `Datasource.native_coordinates` that is not implemented in the base class.

But really I'm not really proposing a big change here. The DataSource still has a `native_coordinates` trait, a `@tl.default` method that calls `get_native_coordinates`, and a `get_native_coordinates` method that is not implemented. The only difference is that the `native_coordinates` trait is read_only, so it cannot be provided at instantiation.

```
class DataSource(Node):
    native_coordinates = tl.Instance(Coordinates, read_only=True)
    
    @tl.default('native_coordinates):
    def _default_native_coordinates(self):
        return self.get_native_coordinates()

    def get_native_coordinates(self):
        raise NotImplementedError()
```

I think the inheritance is quite flexible an unsurprising. Subclasses with computed `native_coordinates` have three options, all of which will work:
 * implement `get_native_coordinates`
 * overwrite the `native_coordinates` trait with a property
 * write their own `@tl.default('native_coordinates')` method

Subclasses that require the `native_coordinates` to be supplied should redefine the trait as `native_coordinates = tl.Instance(Coordinates).tag(attr=True)`. This works as expected, the tl.default from the super class is *not* called, so if you don't provide a value at instatiation, you get a `tl.TraitError` when you reference `native_coordinates`.

Tthis all works in reverse, too. If the base node has `source = tl.Unicode().tag(attr=True)`, subclasses with computed `source` have two options, both of which will work
 * overwrite the `source` trait with a property
 * redefine the source trait as `source = tl.Unicode(read_only=True)` and write a `@tl.default` source method

Again, I see no advantages of this scheme over just using properties alongside private variables to avoid recomputing. We could even keep `get_native_coordinates` and have the property call it. So if you are interested by that simplification, with or without `get_native_coordinates`, please do let me know.

**Comment by jmilloy** [comment]
Assuming the trait + `@tl.default` + `get_*` version above, we can cache computed traits in the `@tl.default` method. 

```
class DataSource(Node):
    native_coordinates = tl.Instance(Coordinates, read_only=True)
    cache_native_coordinates = tl.Bool(True)
    
    @tl.default('native_coordinates):
    def _default_native_coordinates(self):
        if self.has_cache(key='native_coordinates'):
            nc = self.get_cache(key='native_coordinates')
        else:
            nc = self.get_native_coordinates()
            if self.cache_native_coordinates:
                self.put_cache(nc, key='native_coordinates')
        return nc

    def get_native_coordinates(self):
        raise NotImplementedError()
```

Note that the value is stored as a public read-only trait, so we are only talking about podpac's caching for speeding up other instances of the node (with RAM caching) or future sessions (disk caching).
Or the subclasses can cache the value in the `get_*` methods:

**Comment by mpu-creare** [comment]
> Again, I see no advantages of this scheme over just using properties alongside private variables to avoid recomputing

Could you give me a code example of this? To contrast with what you have above? 

I think that your suggestion (and our adoption) of going to read-only traits warrants reconsidering what we're doing here as well. Could simplify everything.

**Comment by jmilloy** [comment]
The traitls-less DataSource `native_coordinates` might look like:

```
class DataSource(Node):
    @property
    def native_coordinates(self):
        if not hasattr(self, '_native_coordinates'):
            self._native_coordinates = self.get_native_coordinates(self)
        return self._native_coordinates

    def get_native_coordinates(self):
        raise NotImplementedError()

# child implements get_native_coordinates
class MyDataSource(DataSource):
    def get_native_coordinates(self):
        ...

# child requires native_coordinates argument
class Array(DataSource):
    def __init__(self, native_coordinates=None):
        if not isinistance(native_coordinates, Coordinates):
            raise TypeError()
        self.native_coordinates = native_coordinates

# child requires native_coordinates argument, which is then read only
class Array(DataSource):
    def __init__(self, native_coordinates=None):
        if not isinistance(native_coordinates, Coordinates):
            raise TypeError()
        self._native_coordinates = native_coordinates
```

A version without `get_native_coordinates`

```
class DataSource(Node):
    @property
    def native_coordinates(self):
        raise NotImplementedError()

# child implements native_coordinates, with a cache decorator
class MyDataSource(DataSource):
    @cached_property
    def native_coordinates(self):
        ...

# child requires native_coordinates argument, which is then read only
class Array(DataSource):
    def __init__(self, native_coordinates=None):
        if not isinistance(native_coordinates, Coordinates):
            raise TypeError()
        self.native_coordinates = native_coordinates

# child requires native_coordinates argument, which is then read only
class Array(DataSource):
    def __init__(self, native_coordinates=None):
        if not isinistance(native_coordinates, Coordinates):
            raise TypeError()
        self._native_coordinates = native_coordinates

    @property
    def native_coordinates(self):
        return self._native_coordinates
```

This still lacks a mechanism for specifiying that an attribute should be included in the node definition. Do you want me to work that out in an example, too?

**Comment by jmilloy** [comment]
An good in-between might be to use traits for provided values and properties for computed values, without the `@tl.default` and `get_*` stuff.

```python
class DataSource(Node):
    source = tl.Unicode().tag(attr=True)

    @property
    def native_coordinates(self):
        raise NotImplementedError()

# child implements native_coordinates, with a cache decorator
class MyDataSource(DataSource):
    @cached_property
    def native_coordinates(self):
        ...

# child requires native_coordinates argument, which is read-only and tagged as an attr
class Array(DataSource):
    trait = tl.Instance(Coordinates).tag(attr=True)

# child has a computed source and native_coordinates
```python
class DataSource(Node):
    @cached_property
    def source(self):
        ...

    @cached_property
    def native_coordinates(self):
        ...
```

We've sort of been mis-using `@tl.default` for properties because we wanted them to sometimes not have to be properties. But maybe the above is the best of both worlds: type definitions and type checking for actual attributes, less __init__ boilerplate, easy trait tagging, and simple properties when appropriate.

**Comment by mpu-creare** [comment]
This last example works for me. Just one detail. 

The 'cached_property' decorator -- is it possible to specify a cache type? What if you just want it cached in ram, but not through the PODPAC caching system? (i.e. similar to using the `_native_coordinates`  private attribute in your traitsless example). Do you EVER want that? It's nice that the PODPAC cache will be shared across different nodes of the same type. 

Would this change also eliminate the custom JSON definitions that we have for data sources and algorithms right now? Probably some of it, but not all of it. 

THanks Jeff! I'm glad someone's thinking about this stuff.

**Comment by jmilloy** [comment]
> Would this change also eliminate the custom JSON definitions that we have for data sources and algorithms right now?

It really does simplify and often eliminate the custom base_definitions.

I guess I was thinking that there would be one cache decorator for object-only caching and a different one for podpac caching, i.e. `@cached_property` that does the `_native_coordinates` thing and `@cache_fun(<key>)` that does podpac caching.

 > Do you EVER want that?

Yeah, that's a good point, I don't think there is really a drawback to using podpac's RAM cache instead of a object-local private attribute.

The `@cache_func` decorator relies on the node `cache_ctrl` object, which I still find somewhat tedious and confusing. Wouldn't it be nice to be able to use `@cache_func(disk=True)` on a per-property basis, and not have to worry about providing a default `cache_ctrl` containing a disk `cache_store` to every node that wants one? That sounds maybe like what you are asking for.

So, I think a single decorator could work just fine.

 * `@cached_property` - defaults: podpac ram cache using the property name 
 * `@cached_property(disk=True, key=<my_key>)` - podpac caching to ram and disk using a custom key

If we do want to allow object-level caching, maybe the options are:

 * `@cached_property` - defaults: object-level caching using underscore
 * `@cached_property(ram=True)` - podpac caching to ram using property name as key
 * `@cached_property(ram=True, disk=True, key=<my_key>)` - podpac caching to ram and disk using a custom key

**Comment by mpu-creare** [comment]
How about: 
```python
@cached_property  # object-level cache with underscore
@cached_property(type='default')  # Uses the global podpac settings
@cached_property(type=['ram', 'disk'])  # Uses PODPAC caching, starting with ram, then falling back to disk
```
Basically I don't like the cache-specific keyword arguments. And I think the key specification is fine.

**Comment by jmilloy** [comment]
**Describe the solution you'd like, updated**

 * Traits tagged as `attr=True` will be included in the Node definition
   * This means they will be included when serializing the Node, when creating a Node hash for caching, and when comparing node equality.
   * Datasource.source, Datasource.interpolator, Compositor.sources, and Algorithm.inputs should be tagged as `attr=True` when appropriate like everything else, without requiring special handling.
 * Computed values should use properties.
   * This means they won't/can't be tagged and included in the Node definition, so they won't cause deadlock when caching.
   * A decorator will facilicate caching properties to the object or to ram/disk/etc using the podpac cache, as described above. This might be an extension of the existing `cache_func` or might be a new decorator.

**Comment by jmilloy** [comment]
> How about:
> 
> ```python
> @cached_property  # object-level cache with underscore
> @cached_property(type='default')  # Uses the global podpac settings
> @cached_property(type=['ram', 'disk'])  # Uses PODPAC caching, starting with ram, then falling back to disk
> ```
> 
> Basically I don't like the cache-specific keyword arguments. And I think the key specification is fine.

We're going to simplify this to `@cached_property` which uses an object-level private attribute and the Nodes `cache_ctrl`, if it exists.

**Comment by jmilloy** [comment]
@mpu-creare the `test_node.py::TestCaching::test_cache_property_decorator` test changes a node attribute which *changes the node definition. I feel like Nodes are generally meant to be read-only, at least as far as attributes and definition. Can you explain what you are testing there, and is it still necessary?

I implemented the `cached_property` and used where I thought it made sense, which includes the Node definition. But that causes that test to fail.

**Comment by mpu-creare** [comment]
That test preceded read-only attributes. The second argument to that decorator I believe is a dependency -- so whenever the other trait was updated, it would fire. It was a pretty tricky decorator to write, so I'd like to keep it. For the test, you can just remove the tagging of those attributes and all should be well.

**Comment by jmilloy** [comment]
Removing the tagging didn't cause the test to pass. Can you take a look? I can take a closer look at what you are trying to test, but you might be a lot more efficient... let me know.

**Comment by mpu-creare** [comment]
I'll have a look next week.

**Comment by mpu-creare** [comment]
Had a look. It's fine just to remove the test, since you also removed `cache_func`, which dealt with dependencies. The new decorators do not deal with dependencies (I assume, I didn't actually check).

**Comment by jmilloy** [comment]
I just moved `cache_func` to the utils. I wanted to use the cached_property in the `Node`, so it has to be defined somewhere before Node is defined. I just moved cache_func along with it.
