### ISSUE TITLE
Pipeline refactor

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#36]
**Description**
Pipelines should be usable as inputs into Nodes (and by other pipelines) and should only allow a single output. Note also that Pipelines will no longer attempt to manage execution.

**Describe the solution you'd like**
The Pipeline class should be converted into a Node. It will still accept a JSON pipeline definition as input and execute that pipeline in its execute method. The spec will be updated to support only a single output node and type in each pipeline definition.

This replaces the PipelineNode class.

**Comment by jmilloy** [comment]
@mpu-creare I've updated the pipeline to allow only a single output. Here's a sample pipeline definition:

```
{
    "nodes": {
        "sm": {
            "node": "datalib.smap.SMAP",
            "attrs": {
                "product": "SPL4SMAU.003",
                "interpolation": "bilinear"
            }
        },
        "twi": {
            "node": "core.data.type.WCS",
            "source": <WCS_SERVER_URL>,
            "attrs": {
                "layer_name": <WCS_LAYER_NAME>
            }
        },
        "twi_bar": {
            "node": "core.data.type.WCS",
            "source": <WCS_SERVER_URL>,
            "attrs": {
                "layer_name": <WCS_LAYER_NAME>
            },
            "evaluate": false
        },
        "twi_bar_reprojected":{
            "node": "core.data.type.ReprojectedSource",
            "inputs": {
                "source": "twi_bar",
                "coordinates_source": "sm"
            },
            "attrs": {
                "interpolation": "bilinear"
            }
        },
        "downscaled_sm": {        
            "node": "Arithmetic",
            "inputs": {
                "A": "sm",
                "B": "twi",
                "C": "twi_bar_reprojected"
            },
            "params": {
                "kappa": "13",
                "tsmtr": "0.3", 
                "eqn": "A + {tsmtr} / {kappa} * (B - C)"
            }
        }
    },
    "output": {
        "node": "downscaled_sm",
        "mode": "file",
        "format": "pickle",
        "outdir": "out_test"
    }
}
```

However, I noted that the output node *has* to be the last node in the "nodes" (because nodes can only reference previously defined nodes, and any unused nodes throws an exception). What do you think about removing the "node" property altogether?

```
    "output": {
        "mode": "file",
        "format": "pickle",
        "outdir": "out_test"
    }
```

It is essentially redundant, but it does add clarity. It's also plausible that we might allow the nodes to be defined in any order in the future, so the node would be required.

On the other hand, I made the default mode 'none'. You can just use this when you don't need a special output:

```
    "output": {
        "node": "downscaled_sm"
    }
```

If we remove the redundant "node" property, then you don't have to include the output section in that case at all, which is quite nice:

```
{
    "nodes": {
        "sm": {
            "node": "datalib.smap.SMAP",
            "attrs": {
                "product": "SPL4SMAU.003",
                "interpolation": "bilinear"
            }
        },
        "twi": {
            "node": "core.data.type.WCS",
            "source": <WCS_SERVER_URL>,
            "attrs": {
                "layer_name": <WCS_LAYER_NAME>
            }
        },
        "twi_bar": {
            "node": "core.data.type.WCS",
            "source": <WCS_SERVER_URL>,
            "attrs": {
                "layer_name": <WCS_LAYER_NAME>
            },
            "evaluate": false
        },
        "twi_bar_reprojected":{
            "node": "core.data.type.ReprojectedSource",
            "inputs": {
                "source": "twi_bar",
                "coordinates_source": "sm"
            },
            "attrs": {
                "interpolation": "bilinear"
            }
        },
        "downscaled_sm": {        
            "node": "Arithmetic",
            "inputs": {
                "A": "sm",
                "B": "twi",
                "C": "twi_bar_reprojected"
            },
            "params": {
                "kappa": "13",
                "tsmtr": "0.3", 
                "eqn": "A + {tsmtr} / {kappa} * (B - C)"
            }
        }
    }
}
```

Long question, just need a quick answer!

**Comment by mpu-creare** [comment]
A few notes based on my usage of these JSON pipelines: 
* While debugging a complex pipeline, it would be nice just to change the "node" in the output and then see the output from that piece of the pipeline
    * This means there might be un-used nodes
    * Right now I have to manually delete these to get at the output I want
    * Problem is now you could have garbage pipelines with tonnes of unused nodes
    * perhaps you can have a: "allow_unused_nodes: true" flag to deal with this debugging... 
* I vote for **keeping the "node" property**, but make it default to the last-defined node
    * I really like your last example, so clean
    * Having sanely defined defaults like you suggested would be great
    * So then the "node" property is optional, still exists, but you don't have to define it... 

Does that answer you long question? Or did I miss a piece?

**Comment by jmilloy** [comment]
Great. What I've already got committed at the moment is actually with "node" optional, defaulting to the last-defined, so we're on the same page. I'll leave it as-is.

I think we should just switch the unused nodes exception to a warning. Maybe I was being overly strict adding that in the first place.

**Comment by mpu-creare** [comment]
Exactly!
