### ISSUE TITLE
Projection to a different CRS should allow Uniform Coordinates as a result

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#362]
**Description**
Right now whenever I transform coordinate to a different system, I ALWAYS get a dependent coordinate system, even though the transformation can be described as uniform. This hinders export to GeoTIFF, which requires Uniform or Rotated coordinate system. This in-turn hinders the WCS capability, or at least makes the WCS capability much less useful, as it requires you to work in a single CRS for your whole pipeline. 

**Describe the solution you'd like**
Whenever possible, I would like transformed coordinates to be as succinctly represented as possible. 

**Sample Code**
```python
>>> c = Coordinates([clinspace(0, 2, 3, "lat"), clinspace(1, 4, 4, "lon")])
>>> c
Coordinates (EPSG:4326)
	lat: UniformCoordinates1d(lat): Bounds[0.0, 2.0], N[3], ctype['midpoint']
	lon: UniformCoordinates1d(lon): Bounds[1.0, 4.0], N[4], ctype['midpoint']
>>> c2 = c.transform('EPSG:3395')
>>> c2
Coordinates (EPSG:3395)
	lat,lon[lat]: DependentCoordinates(i,j->lat): Bounds[0.000000, 221194.077168], shape(3, 4), ctype[midpoint]
	lat,lon[lon]: DependentCoordinates(i,j->lon): Bounds[111319.490793, 445277.963173], shape(3, 4), ctype[midpoint]
>>> c2['lat'].coordinates
array([[7.08115455e-10, 7.08115455e-10, 7.08115455e-10, 7.08115455e-10],
       [1.10579965e+05, 1.10579965e+05, 1.10579965e+05, 1.10579965e+05],
       [2.21194077e+05, 2.21194077e+05, 2.21194077e+05, 2.21194077e+05]])
>>> c2['lon'].coordinates
array([[111319.49079327, 222638.98158655, 333958.47237982, 445277.96317309],
       [111319.49079327, 222638.98158655, 333958.47237982, 445277.96317309],
       [111319.49079327, 222638.98158655, 333958.47237982, 445277.96317309]])
```

**Additional context**
I realize this is an optimization. It hasn't been an issue since starting to work on GeoTIFF export. I wonder if there is a simple test you can do (just transform a few points) to make sure the resultant coordinate system is still uniform (i.e. lines remain lines through the transformation). Shouldn't be a tough check, if you test 9 points within the rectangle, for example. Or perhaps pyproj will give you this information somehow through the internals...

**Comment by jmilloy** [comment]
Makes sense. I'd love to be able to do it without the empirical test, and I looked into it a little bit.
 - The `pyproj.Transformer` object has an `operations` attribute that is empty for the example you give above, but not empty in another case where the uniform grid is not maintained. So I'm wondering if it's as simple as that.
 - Another thought was to compare the crs `datum`, which must be the same, and then also check some parameters of the projection (I'm just not sure which ones to check or what exactly to check for yet).

**Comment by jmilloy** [comment]
I asked a question here. Someone made the claim that 4326 -> 3395 will scale differently at different latitudes, and that we would only maintain a uniform grid in small areas. I wasn't able to reproduce that, but if it is true, or true in some cases, an empirical test for the specfic area requested is the only way to go.

**Comment by mpu-creare** [comment]
Nice question. Empirical test does seem like the most robust way forward... albeit a little annoying.

**Comment by jmilloy** [comment]
If we have a uniform grid, the transformed coordinates may be
 - still a uniform grid (we can still use UniformCoordinates)
 - still a grid, but no longer uniform (requiring ArrayCoordinates)
 - no longer a grid (requiring DependentCoordinates)

The 4236 -> 3395 case maintains the uniform grid at some latitudes, but not all. I agree now that the empirical test is the best way to handle this.

**Comment by mpu-creare** [comment]
see #396
