### ISSUE TITLE
Update or remove AirMoss

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#378]
**Description**

The AirMoss datalib is very out of date.
 * `AirMOSS` does not define its sources
 * `AirMOSS_Site` does not define its sources
 * `AirMOSS_Site` defined `native_coordinates` instead of `source_coordinates` and/or `shared_coordinates`

**Steps to Reproduce**

Run podpac/datalib/airmoss.py

**Additional Notes**

I was unable to get my credentials to work in the first place. If it will be a lot of work to update, we should just remove it before 2.0.

**Comment by jmilloy** [comment]
@mpu-creare I looked at this for a minute. I think you'll probably just want to remove it.

**Comment by jmilloy** [comment]
Currently need to run podpac/datalib/airmposs.py in the feature/attr-improvements branch.

**Comment by mpu-creare** [comment]
I had a look at it too. I can't get the opendap endpoint to work either. I think we're probably better off using the EGI endpoint, which is a brand new implementation. So I concur, scrap it for now.

**Comment by mpu-creare** [comment]
Done in #370
