### ISSUE TITLE
Add podpac version to node definition / hash

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#390]
**Description**
Nodes may change between versions. Including the podpac version in the hash would avoid silent cache-related errors across upgrades.

**Describe the solution you'd like**
The podpac version could be included in the definition as a node attr. It should be added explicitly when loading a JSON definition, since users are likely to omit it. Another option would be to include the version only when computing the hash.

**Additional context**
Avoiding computing default values for traits when accessing the cache would be helpful in some contexts. E.g. see #389. We have implemented, reverted, and discussed omitting default traits from the node definition in order to do this. There are drawbacks to that (less affordance for users, hacks required with traitlets containers such as List and Dict), but in addition, node defaults may change between versions. This would fix that issue.

**Comment by jmilloy** [comment]
@mpu-creare Should this be the whole version, or maybe just the major version (e.g. 1 vs 2)?

**Comment by mpu-creare** [comment]
Ugh... let's do whole version? This requires some discipline to not change defaults in minor releases... but I think finer-grained would be too much of a headache. 

Will the cache hash depend on the podpac version? Or should that be stripped out of the hash?

**Comment by jmilloy** [comment]
Hmm.

At this point, I think I've fixed the deadlock issue without having to omit default traits, so this is now no longer related to that.

I thought part of the point was to include the version in the cache hash. That's why I wondered if the major version might be enough. But if it is just cosmetic, then sure, we can strip it out of the hash, and I see no reason not to include the whole version.

Or do you imagine `Node.from_definition` and `Node.from_json` should fail if the version doesn't match?

**Comment by mpu-creare** [comment]
I just came across that. I want the version more for the sake of provenance (i.e. tracking how/when someone did a computation and how to reproduce it). 

In that case, let's do the whole version but make sure that it's ignored for the cache hash or when recreating nodes. In the future maybe we'd want the pipeline to fail on `from_definition` -- that's not a bad idea. At least let users know they need to upgrade PODPAC.... or downgrade...

**Comment by jmilloy** [comment]
Roger.
