### ISSUE TITLE
Public API when importing PODPAC

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#40]
**Description**
What should be the root level imports when you `import PODPAC`?

**Describe the solution you'd like**
We could have a flat structure where all the nodes are available at import. That's currently the approach:
```python
import podpac
dir(podpac)
['Algorithm',
 'Arithmetic',
 'CACHE_DIR',
 'Compositor',
 'Convolution',
 'Coord',
 'Coordinate',
 'Count',
 'DataSource',
 'ExpandCoordinates',
 'Kurtosis',
 'Max',
 'Mean',
 'Median',
 'Min',
 'MonotonicCoord',
 'Node',
 'OrderedCompositor',
 'Pipeline',
 'PipelineError',
 'PipelineNode',
 'SinCoords',
 'Skew',
 'SpatialConvolution',
 'StandardDeviation',
 'Style',
 'Sum',
 'TimeConvolution',
 'UniformCoord',
 'Units',
 'UnitsDataArray',
 'UnitsNode',
 'Variance',
 'coord_linspace',
 'core',
 'settings']
```

Or we could have a more categorical or hierarchical approach.

**Comment by mpu-creare** [comment]
I prefer the more categorical/hierarchical approach. 

```python
import podpac
['algorithm',
 'algorithmlib',
 'compositor',
 'coordinate',
 'data',
 'datalib',,
 'Node',
 'pipeline',
 'Units',
 'UnitsDataArray',
 'core',
 'settings']

dir(podpac.algorithm)
[
'Algorithm',
'Arithmetic',
 'Convolution',
 'Count',
 'ExpandCoordinates',
 'Kurtosis',
 'Max',
 'Mean',
 'Median',
 'Min',
 'SinCoords',
 'Skew',
 'SpatialConvolution',
 'StandardDeviation',
 'Sum',
 'TimeConvolution',
 'Variance',
]

dir(podpac.compositor)
[
'Compositor',
 'OrderedCompositor',
]

dir(podpac.data)
[
'DataSource', 
'NumpyArray', 
'WCS', 
...
]

dir(podpac.pipeline)
[
 'Pipeline',
 'PipelineError',
]

dir(podpac.coordinate)
[
'Coordinate', 
'Coord', 
'MonotonicCoord', 
'UniformCoord', 
'coord_linspace', 
...
]
```
etcetera.

**Comment by mpu-creare** [comment]
@jmilloy @mlshapiro @drc-creare and DS what do you think?

**Comment by jmilloy** [comment]
I wouldn't be strict one way or the other.

Note that providing a flat structure doesn't prevent nested use (e.g. you can use either Median or algorithm.Median or algorithm.stats.Algorithm in a pipeline), but I do think that the toplevel namespace will get too cluttered.

Currently we have a mix: for example, the nodes in the various algorithm submodules are all exposed at the algorithm level (so not entirely flattened but not entirely nested either), which I think makes sense. So I would honestly expose highly common things at the podpac level (e.g. `from podpac import Coordinate`, but from `podpac.core.coordinate import Coord`).

**Comment by mlshapiro** [comment]
Documented in contributing in cbaa4985bbcf24246337577996b88523c3976ea5
