### ISSUE TITLE
ScipyGrid interpolator should not allow source coordinates with length-1 dimensions

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#400]
**Description**

The ScipyGrid interpolator allows interpolation using source coordinates with a single point in some dimensions. This throws a `true_divide` warning when using the RegularGridInterpolator. I don't believe that RegularGridInterpolator is meant to handle singleton dimensions (e.g. see https://github.com/scipy/scipy/issues/7560).

**Steps to Reproduce**

I found this testing the `COSMOSStation` datasource, which specifically handles a single lat-lon source point (clearly not a grid): 

```
python podpac/datalib/cosmos_stations.py
```

**Observed Behavior**

```
/home/jmilloy/Creare/Pipeline/_podpac-3.8_/lib/python3.8/site-packages/scipy/interpolate/interpolate.py:2536: RuntimeWarning: divide by zero encountered in true_divide
  norm_distances.append((x - grid[i]) /
/home/jmilloy/Creare/Pipeline/_podpac-3.8_/lib/python3.8/site-packages/scipy/interpolate/interpolate.py:2536: RuntimeWarning: invalid value encountered in true_divide
  norm_distances.append((x - grid[i]) /
/home/jmilloy/Creare/Pipeline/_podpac-3.8_/lib/python3.8/site-packages/scipy/interpolate/interpolate.py:2519: RuntimeWarning: invalid value encountered in less_equal
  idx_res = [np.where(yi <= .5, i, i + 1)
```

**Expected Behavior**

Run with no warnings.

**Additional Notes**

I believe the fix to the `ScipyGrid` interpolator is to update its `can_interpolate` to check `source_coordinate['lat'].size > 1` and same for lon. However, doing so breaks the COSMOS Stations datalib:

```
InterpolationException: Dimensions ['time', 'lon', 'lat'] can't be handled by interpolation definition:
 Interpolation
	('default',): nearest, ['NearestNeighbor', 'Rasterio', 'ScipyPoint', 'ScipyGrid'], {'spatial_tolerance': 1.1, 'time_tolerance': numpy.timedelta64(1,'D')}
```

I believe the `ScipyPoint` interpolator should handle this case. In order to do so most easily, the source_coordinates could be converted from an "unstacked point" to a "stacked point".

Lastly, it seems that the `ScipyGrid` interpolator (via `RegularGridInterpolator`) actual does interpolate points as desired, at least in some cases. That would mean "extrapolating" in the nearest case and NaN in the other cases. In that case, another solution would just be to ignore the warnings.

**Comment by jmilloy** [comment]
It's tough. The ScipyPoint interpolator thinks it can only handle lat_lon coordinates without an associtated time coordinate. So even changing the `COSMOSStation` to stacked lat_lon didnt work. I'm not sure what the best solution is, and I suspect there are other issues that outline this same problem in other words.

**Comment by mpu-creare** [comment]
The interpolation needs work...

**Comment by mpu-creare** [comment]
COSMOS not working for 2.0.0 is "ok"

**Comment by mpu-creare** [comment]
I believe with the new `NearestNeighborInterpolator` and `XarrayInterpolator` as part of #430, this issue is now moot... those two interpolators will be selected before this one. I'm marking this as `wontfix` and moving on.
