### ISSUE TITLE
Cant import "modis-pds" module

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#404]
**Description**

In the datalib, modis access in a module named `modis-pds` which can't be imported

**Steps to Reproduce**

```
from python.datalib import modis-pds
```

**Expected Behavior**

It should be named something can be imported

**Additional Notes**

I'm going to rename `modis` on develop unless there are any issues.

**Comment by mlshapiro** [comment]
@jmilloy @mpu-creare this is for documentation and reference in case there are future questions. Pushing to develop now

**Comment by mlshapiro** [comment]
fixed in d34f28e336a602bc828fb2740fb6ec6d058e35b2

**Comment by jmilloy** [comment]
Ah, silly error! It really should be modis_pds, since there are other modis data sources available (and modis-pds seems to be possibly deprecated).

**Comment by mlshapiro** [comment]
Got it - I'll rename "modis_pds"

**Comment by mlshapiro** [comment]
and i'll remove from __init__ not to pollute the namespace

**Comment by mlshapiro** [comment]
finished in 1f3f1f89fa23b47023a0f8e5ed524258012db006
