### ISSUE TITLE
PROPOSAL: Compositors need to specify composition dimensions

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#406]
**Description**
The `TerrainTiles` compositor only works if time is NOT specified. This should not be. The reason this happens is because the compositor calls `Node.create_output_array(coordinates)` using the user-input coordinates, which could contain additional dimensions. 

**Describe the solution you'd like**
Compositors should have a `composite_dims` attribute and overwrite `Node.create_output_array` to automatically drop any dims in coordinates not in `self.composite_dims`. 

**Sample Code**
```python
coords = Coordinates([[0], [1], [2]], ['lat', 'lon', 'time'])
TerrainTiles(zoom=6).eval(coords)  # Fails right now
TerrainTiles(
    zoom=6,
    composite_dims=['lat', 'lon']  # Should succeed in the future (and should be hard-coded in TerrainTiles Node
).eval(coords)
```

**Additional context**
This is a proposal open for discussion. I do have a fix in OrderedCompositor's `composite` method, but it seems like this problem is more general.

**Comment by mpu-creare** [comment]
@mlshapiro @jmilloy what do you guys think?

**Comment by mpu-creare** [comment]
Actually, probably you should just drop the extra coordinates on eval...

**Comment by jmilloy** [comment]
#407 merged.
