### ISSUE TITLE
Running Unit Tests Change my local settings

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#421]
**Description**
Whenever I run the unit tests, my local setting change

**Steps to Reproduce**
```
pytest podpac
```

**Expected Behavior**
Unit tests should NOT change MY settings

**Observed Behavior**
Unit tests DO change MY settings

**Additional Notes**
Probably make a custom class with setup/teardown methods that all unit tests can use so that this case is handled. Maybe a module-level (i.e. file level?) setup and teardown?

**Comment by jmilloy** [comment]
4c3a3223
