### ISSUE TITLE
Collaboration with Satpy

### ISSUE THREAD

**Issue by djhoese** [creare-com/podpac#440]
**Description**

I found out about podpac through Mattheus' AMS poster, but the website errors out for any of the ways I'm supposed to be able to contact you. It seems like podpac could benefit from or perhaps leverage some of the work done by the Pytroll Satpy project:

https://satpy.readthedocs.io/en/stable/

I'm one of the core developers on this project and would be happy to answer any questions. I'm not sure I full understand everything under the hood of podpac, but I think we could help each other out. We've been working more on reading data from S3 and have plans for making things more compatible with other popular scientific python tools like the Intake library (popular in the Pangeo community) and trying to use the fsspec library where possible. Satpy is completely dependent on xarray and dask for re-usability and performance. Does podpac use any of these libraries?

Edit: If it wasn't clear, Satpy helps read, resample, and write various meteorological satellite data formats (mostly imagers).

**Comment by mpu-creare** [comment]
@djhoese it seems like there's a lot of overlap between our efforts. I'd be happy to chat specifically. 

Briefly, yes, podpac uses a lot of the same technology. The basic premise of podpac is to get data from wherever it's stored in whatever format of whatever datatype (grids, vs. points etc) into harmonized xarray objects. So, a bit broader in scope than `Satpy`, but we also depend completely on `xarray`, and have some support for dask and intake. 

The main differences in our project (besides scope) is that podpac is structured as a reproducible pipeline architecture. What that means is we specify how to get from inputs to outputs (through compositors, equations, whatever), recording every step along the way so that it can be reproduced. We also have some cloud integration making it easy share pipelines, and we do some caching along the way as well.

 We've really worked very hard on making our code modular, so that we can easily add new Nodes to support libraries like `Satpy`. 

Basic mapping between projects satpy -- > podpac: 
* Readers --> podpac `Datasource` nodes
* Resample --> Interpolator objects / Interpolation Nodes. 
* Compositors --> Compositors, roughly, perhaps with a mix of algorithm nodes
* Enhancements --> Algorithm nodes

**Comment by djhoese** [comment]
Very cool. A couple questions that come to mind that might help us head toward the same workflows:

1. How are you storing and defining this history of steps used to reproduce a specific output? Can I use podpac to save a geotiff and is that history added to the geotiff in some way?
2. Have you had to define "standard" RGB composites anywhere? Have you nailed down who/what source is **the** definition for these recipes?
3. Where can I find out more about this cloud integration that you are talking about? Like I mentioned we use dask for everything and are doing more and more with dask-friendly loading of remote (cloud) data. Beyond playing with some jupyterlab instances and running our dask workflows there, I don't think we have anything like your describing.

Additional notes: Some of our compositors are "algorithms" I think. They aren't always simple RGB composites but can include rayleigh correction, sharpening techniques, various normalization techniques (like those used for VIIRS DNB), etc.

**Comment by mpu-creare** [comment]
1. We have a JSON format to store the series of `Nodes` that define a processing pipeline. You could certainly embed the JSON in the metadata of a GeoTIFF -- and then you can recreate the processing pipeline from the source data using the JSON string.  For a simple example creating a pipeline from JSON see [here](https://github.com/creare-com/podpac-examples/blob/develop/notebooks/4-advanced/pipeline-from-JSON.ipynb), with a more complicated pipeline definition created as part of our [Drought Monitor Demo](https://github.com/creare-com/podpac-drought-monitor/blob/develop/notebooks/new/Drought-Monitor-Pipeline.ipynb).
2. Not really. But it shouldn't be too hard to write a RGB compositor, and our internal pipeline will keep track of where the data sources come from. 
3. The basic premise for our cloud integration is being able to run any algorithm pipeline on AWS by wrapping it in a `Lambda Node` (seamless cloud transition). This lets you run parts of your algorithm on the cloud, or create web apps to share data.   The drought monitor is an example cloud application, see here: https://github.com/creare-com/podpac-drought-monitor and you can run it here: https://creare-com.github.io/podpac-drought-monitor/html/ . This website uses AWS lambda functions, so no server constantly running, and the data is hosted on S3. To create the Lambda function, see here: https://github.com/creare-com/podpac-examples/blob/develop/notebooks/4-advanced/aws-lambda.ipynb for a general description, with the actual notebook to create the drought monitor here: https://github.com/creare-com/podpac-drought-monitor/blob/develop/notebooks/MakeLambdaFunction.ipynb . 

BTW, I also could not figure out how to connect with you over the AMS app. I did try to share my business card with you, so you should have my contact information. If not, let me know and I'll find a way to get it to you.

**Comment by djhoese** [comment]
1. Interesting. My main reason for asking about geotiffs was that I usually get requests for some level of "history" and people want it in the output file like NetCDF CF "history" or in a geotiff's metadata. If this isn't something you've run into then good.
2. My main reason for asking is that in our experience with Satpy everyone has their own way of creating certain RGB composites and each one has slightly different inputs or color limits or an extra enhancement, but each one of those variations has the same name. There isn't really an organized list of recipes and I was hoping you had found one or come up with one.
3. This is really cool! It makes a lot of sense. Based on the JSON I feel like it wouldn't be that hard to wrap the various high-level components of Satpy and do something similar as kind of a "plugin" to podpac.

I've been using the AMS website and...nothing good has come of it. I'm ok communicating over github for a bit, otherwise the pytroll group (who maintains Satpy) has a slack that I'm always on, or you can send me an email through the SSEC contact form here: https://www.ssec.wisc.edu/contact-form/?contact-name=Hoese,%20Dave

**Comment by mpu-creare** [comment]
@djhoese sorry for the sudden radiosilence there on my part last week. 

>Based on the JSON I feel like it wouldn't be that hard to wrap the various high-level components of Satpy and do something similar as kind of a "plugin" to podpac.

I'll create an issue for this. And yes, I don't think it would be too hard to do this.

**Comment by mpu-creare** [comment]
Stale. Closing.
