### ISSUE TITLE
Integration tests for datalibs

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#442]
**Description**

The datalib nodes rely on external resources with urls, data keys, and organization structures that can change, breaking the podpac datalibs.

**Describe the solution you'd like**

Simple integration tests that run nightly or weekly on TravisCI for datalibs.

Podpac core has good unit test coverage that runs on every commit. We are adding tests for datalibs for the 3.0.0 release which must be run manually. We should mark some specific datalib tests for `nightly_integration` which will notify us quickly when we need to push a hotfix because a url or other volatile resources has changed.

**Comment by mpu-creare** [comment]
datalib was moved to [its own repository](https://github.com/creare-com/podpacdatalib), closing.
