### ISSUE TITLE
optional algorithm inputs

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#446]
**Description**
I think it would be useful to be able to define optional algorithm inputs.

**Describe the solution you'd like**
If the input is None, the algorithm will not evaluate it. It will not be in the `algorith` method `inputs`.

**Sample Code**
```
class MyAlgorithm(Algorithm):
    a = tl.NodeTrait() # required
    b = tl.NodeTrait(allow_none=True) # optional

# should work
node = MyAlgorithm(a=SomeDataSource(), b=OtherDataSource())
o = node.eval()

node = MyAlgorithm(a=DataSource)
o = node.eval()

# should fail at initialization
node = MyAlgorithm(b=OtherDataSource())
```

**Comment by jmilloy** [comment]
@mpu-creare Do you see any issues with this?

**Comment by mpu-creare** [comment]
Works for me. It's still up to the algorithm creator to handle optional inputs, but at least this will inform users at the point of creation.

**Comment by jmilloy** [comment]
I don't have a need for this any more.
