### ISSUE TITLE
large xarray dataset source cannot be evaluated

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#447]
**Description**
I get a memory error when I try to evaluate a large netcdf datasource using the podpac `Dataset` node. The existing code `data.data[coordinates_index]` raises `numpy.core._exceptions._ArrayMemoryError` when getting the underlying numpy array `data.data`. But `data[coordinates_index]` doesn't work because of the new fancy indexing.

**Comment by jmilloy** [comment]
@mpu-creare I would suggest that we flatten and then reshape as needed, but I haven't found a where any of the `coordinates_index` items need to be flatten. They can always just be squeezed to a 1d array and left that way. Do you know what case requires truly shaped indexing?

**Comment by jmilloy** [comment]
I replaced

```
return self.create_output_array(coordinates, data.data[coordinates_index])
```

with 

```
index = tuple(np.atleast_1d(idx.squeeze()) for idx in coordinates_index)
return self.create_output_array(coordinates, data[index])
```

It will fail if there is a truly shaped index, but then I will have an example to work with to implement that.

**Comment by jmilloy** [comment]
The above won't work when taking the diagonal, for example. We think the proper solution is to convert the fancy indexes into labeled xarray DataArrays. I'll write a utility funciton to do that.

**Comment by jmilloy** [comment]
https://github.com/creare-com/podpac/blob/develop/podpac/core/interpolation/test/test_selector.py#L219

**Comment by jmilloy** [comment]
@mpu-creare With the above example, flattening the `coordinates_index` works:

```
>>> flattened = tuple(np.atleast_1d(idx.squeeze()) for idx in coordinates_index)
>>> x.data[flattened]
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (4,)
>>> x[flattened]
<xarray.DataArray (time: 2, lat: 2, lon: 4)>
array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [20, 21, 22, 23]]])
Coordinates:
  * time     (time) int64 0 1
  * lat      (lat) int64 0 2
  * lon      (lon) int64 0 1 2 3
>>> np.array_equal(x.data[coordinates_index], x[flattened].data)
True
```

That is, it fails on the numpy array but it works on the xarray DataArray where we need it. It selects the same data so that `x.data[coordinates_index]` and `x[flattened].data` are the same.

Can you maybe give an example of `coordinates_index` where that doesn't work?

**Comment by mpu-creare** [comment]
Ok. I'm on it. It looks like this has to happen at the selector level. Where should I push a fix?

**Comment by jmilloy** [comment]
release/3.0.0

I started to make the "xarray" `coordinates_type` and add another case where we use `_ind2slice` that uses a new `_ind2xarray` function. But I changed my mind because I don't see any other node using it, so you could just put it into `DatasetSource.get_data` directly. Or you can just post whatever the index needs to be for the toy example above and I'll take the time to put it in the code.

**Comment by mpu-creare** [comment]
Wow, apparently I was misremembering the complexity of this... turns out you were totally right. Just flattening the arrays work. I thought I did something fancy to get a tighter sub-selection but I think you can't always do that... so you have to select more than you want. 1e13dfe8446668e929edfa925

I was probably confusing the selector with the NN interpolator, in which case really fancy indexing works.

**Comment by jmilloy** [comment]
Okay! Just to check... I see the xarray type, but I don't see the conversion anywhere yet.

I don't know about the performance aspects of this, but it's not that the DatasetSource has to use "xarray" indices, it's that it *can't* use numpy indices. Slices are fine. It would be nice to leave slices as they are. This is what I have locally as a workaround in the DatasetSource class:

```
    def get_data(self, coordinates, coordinates_index):
        """{get_data}"""

        if not isinstance(self.data_key, list):
            data = self.dataset[self.data_key][self.selection or {}]
            data = data.transpose(*[self._lookup_key(dim) for dim in self.dims])
        else:
            data = self.dataset[self.data_key].to_array(dim="output")[self.selection or {}]
            tdims = tuple(self.dataset.dims) + ("output",)
            data = data.transpose(*tdims)

        if not any(isinstance(idx, slice) for idx in coordinates_index):
            coordinates_index = tuple(np.atleast_1d(idx.squeeze()) for idx in coordinates_index)
            
        return self.create_output_array(coordinates, data[coordinates_index])
```

That if-statement could be changed... if there is a mix, we could flatten numpy arrays and leave slices, for example. Just a thought.

**Comment by mpu-creare** [comment]
@jmilloy it turns out that the conversion really is needed for numpy, but for xarray the 1-d indices computed in the selector are already in the correct format -- so no conversion. 

The indices are actually potentially more efficient than the slices -- the slices have a set stride whereas the indices can have variable strides. The selector will produce whatever you ask for... so we can't ask for both slices and xarray indices... does that make sense?

**Comment by jmilloy** [comment]
> it turns out that the conversion really is needed for numpy, but for xarray the 1-d indices computed in the selector are already in the correct format -- so no conversion.

I don't really follow. But I'll take a look when you commit. I'm gathering that it's not an 'xarray' coordinates_index_type, but I'm not sure yet if *all* numpy coordinates are getting flattened (no new coordinates_index_type), or if you will be adding a "numpy-flat' coordinates_index_type.

> The indices are actually potentially more efficient than the slices -- the slices have a set stride whereas the indices can have variable strides. The selector will produce whatever you ask for... so we can't ask for both slices and xarray indices... does that make sense?

Well, I was wondering if the slice was faster in cases where the stride is uniform (so the slice and the array select the same coordinates). It probably doesn't really matter.

But in fact, I think the selector *will* give you slices even if you ask for 'numpy'. It only does numpy-to-slice conversion, not the other way around! But I think this only happens it is selecting everything, as in `slice(None)`. The way I flattened the indices outside the selector in my workaround meant that I got those slices sometimes and had to / got to avoid converting them.

**Comment by jmilloy** [comment]
Not there yet:

```
(Pdb) _selector
<bound method InterpolationManager.select_coordinates of InterpolationManager
	('default',): nearest, ['NearestNeighbor', 'XarrayInterpolator', 'RasterioInterpolator', 'ScipyPoint', 'ScipyGrid'], {}>
(Pdb) _selector(self.coordinates, coordinates, index_type='slice')
(Coordinates (+proj=longlat +datum=WGS84 +no_defs +vunits=m)
	time: ArrayCoordinates1d(time): Bounds[2018-01-01T00:00:00.000000000, 2018-01-02T00:00:00.000000000], N[2]
	lat: ArrayCoordinates1d(lat): Bounds[0.0, 2.0], N[2]
	lon: ArrayCoordinates1d(lon): Bounds[10.0, 40.0], N[4], (slice(0, 2, 1), slice(0, 3, 2), slice(0, 4, 1)))
(Pdb) _selector(self.coordinates, coordinates, index_type='numpy')
(Coordinates (+proj=longlat +datum=WGS84 +no_defs +vunits=m)
	time: ArrayCoordinates1d(time): Bounds[2018-01-01T00:00:00.000000000, 2018-01-02T00:00:00.000000000], N[2]
	lat: ArrayCoordinates1d(lat): Bounds[0.0, 2.0], N[2]
	lon: ArrayCoordinates1d(lon): Bounds[10.0, 40.0], N[4], (array([[[0]],

       [[1]]]), array([[[0],
        [2]]]), array([[[0, 1, 2, 3]]])))
(Pdb) _selector(self.coordinates, coordinates, index_type='xarray')
(Coordinates (+proj=longlat +datum=WGS84 +no_defs +vunits=m)
	time: ArrayCoordinates1d(time): Bounds[2018-01-01T00:00:00.000000000, 2018-01-02T00:00:00.000000000], N[2]
	lat: ArrayCoordinates1d(lat): Bounds[0.0, 2.0], N[2]
	lon: ArrayCoordinates1d(lon): Bounds[10.0, 40.0], N[4], (array([[[0]],

       [[1]]]), array([[[0],
        [2]]]), array([[[0, 1, 2, 3]]])))
```

**Comment by jmilloy** [comment]
In `Selector.select`, it seems to be returning the correct (non-merged) `coord_inds`, but for some reason it the coordinates_index that the datasource uses is still multi-dimensional. I'm deugging now.

**Comment by jmilloy** [comment]
I guess the InterpolationManager.select_coordinates does some stuff, too. Should have this sorted soon.

**Comment by jmilloy** [comment]
Okay, got it.

**Comment by mpu-creare** [comment]
Thanks for taking this over the finish line @jmilloy
