### ISSUE TITLE
NumpyArray -> NDArray

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#46]
**Description**

Is there a reason to specify `Numpy` in the array DataSource type? Could a naive user implement a list of data (perhaps from a JSON document or an excel spreadsheet?) 

**Describe the solution you'd like**

Rename `NumpyArray` to `NDArray` or something more general

**Comment by jmilloy** [comment]
I agree, I would call it an `ArraySource`.

`DataSource`, ArraySource`, `PyDapSource`, `RasterIOSource`, `WCSSource`, `ReprojectedSource`, `S3Source`, and likely eventually `JSONSource`, `CSVSource`, etc...

**Comment by mlshapiro** [comment]
updated in be6e31f41f6e1743b8095ae55b9710db9be02a5f 

backwards compatible
