### ISSUE TITLE
get source data for Datasource and TileCompositors

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#468]
### Description

It should be easy to get source data (for given bounds) for Datasources and TileCompositors.

### Current

You can get source data from any `Datasource` using the source `coordinates`:

```python3
# all source data
node.eval(node.coordinates)

# within bounds
coords = node.coordinates.select(my_bounds)
data = node.eval(coords)
```

### Proposal

I propose a method to get source data for `Datasource` *and* `TileCompositor` nodes (optionally given bounds for some or all dimensions).

```python3
# all source data
data = node.get_source_data()

# within bounds
data = node.get_source_data(my_bounds)
```

### Implementation

A universal `Datasource.get_source_data` can be implemented that selects and evaluates the source `coordinates`, but the value here (in addition to a more direct API) is that specific subclasses can and should define a more direct implementation whenever possible that avoids the evaluattion and interpolation machinery completely.

**Comment by jmilloy** [comment]
Note you can also use the new `'none'` interpolator, though you have to supply your own coordinates:

```
data = node.eval(my_coords, interpolation='none')
```

**Comment by jmilloy** [comment]
@mpu-creare @jbieszcz This is something that I and others have wanted in podpac for a long time. Does this sound like a reasonable proposal?

**Comment by mpu-creare** [comment]
I'll defer to @jbieszcz . But as a note  `eval` does not support an `interpolation` keyword argument. Are you proposing we make one?

**Comment by jmilloy** [comment]
> But as a note eval does not support an interpolation keyword argument. Are you proposing we make one?

No I guess i was rushing. Updated.

**Comment by jbieszcz** [comment]
The proposal above for `get_source_data` sounds good to me.   Also I assume that if `my_bounds` are passed, there won't be any interpolation (i.e., `my_bounds` are true min/max bounds, with no spacing info)
