### ISSUE TITLE
Latest Pint Module Version not compatible with latest podpac

### ISSUE THREAD

**Issue by alyssamf** [creare-com/podpac#496]
**Description**
When I install latest podpac (podpac==3.1.1), it installs pint (pint==0.20.1). 
These versions are not compatible as I get this error when trying to run my python script using podpac:
ModuleNotFoundError: No module named 'pint.unit'

**Steps to Reproduce**
```
$ conda create -n podpac python=3 anaconda
$ conda activate podpac
$ pip install podpac[all] 
$ python test.py


test.py

from podpac.datalib.terraintiles import TerrainTiles
from podpac import Coordinates, clinspace

node = TerrainTiles(tile_format='geotiff', zoom=8)
c = Coordinates([clinspace(40, 43, 1000), clinspace(-76, -72, 1000)], dims=['lat', 'lon'])

```

**Expected Behavior**
Installing podpac with 
$ pip install podpac[all] 
should install compatible versions of required libraries. 

**Additional Notes**
pint==0.19 and pint==0.18 are both compatible with podpac==3.1.1

**Comment by mpu-creare** [comment]
Thanks for the issue. I'll try to roll out a hotfix sometime this week.

**Comment by mpu-creare** [comment]
Pushed a fix here: https://github.com/creare-com/podpac/releases/tag/3.1.2

Let me know if that solves the issue on your end as well.
