### ISSUE TITLE
Mac install failed with ValueError: scipy.__spec__ is None

### ISSUE THREAD

**Issue by xvThomas** [creare-com/podpac#499]
**Description**
After installing podpac on MacOSX, the following command leads to a "ValueError: scipy.__spec__ is None".

**Steps to Reproduce**
Install python from anaconda distribution https://www.anaconda.com/products/distribution
Then run:
```
% python --version                      
Python 3.9.15
% conda --version
conda 22.9.0
// create podpac environment
% conda create -n podpac python=3 anaconda
// activate podpac
% conda activate podpac
// install
% pip install podpac
// run ipython
% ipython

// import podpac with error
In [1]: import podpac
INFO:numexpr.utils:Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-4dd38f6958f8> in <module>
----> 1 import podpac
...
ValueError: scipy.__spec__ is None
```

Same result with jupyter lab.

Executed on:
- MacOSX 12.6 Apple M1 Pro 32 Go
- MacOSX Ventura 13.0.1 Core i9 64 Mo

**Comment by mpu-creare** [comment]
Hi @xvThomas . It's this line that's causing the problem: https://github.com/creare-com/podpac/pull/497/files#diff-15e2785308e79f70d4b9bf7d848bfcf89804eb5413224c7a044d7441fda93f11L24 . Something recently changed with our dependencies, which is causing the issue. I've made `scipy` a core dependency, so we no longer have to lazy-load it. 

I'm working on the 3.2.0 release, and hope to have it out by the end of the year. In the mean time, you could try installing PODPAC from the release branch: 
```
pip install "podpac[all]@git+https://github.com/creare-com/podpac.git@release/3.2.0"
```

**Comment by xvThomas** [comment]
Thanks @mpu-creare, all is fine now
