### ISSUE TITLE
podpac update - how are times defined/handled?

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#5]
I have a question on how the podpac update to allow requesting a single time was done, because I’ve noticed changes in some of my functions from yesterday.  For example, it now allows me to request times that had no data as of yesterday, so for example, this code returns data in all 5 times, rather than just T06 and T18:
```python 
lat = -34.848
lon = 146.172

step = 0.01 # 201x201 pixels in 2degree by 2degree square area
lat_range = np.arange(round(lat*4)/4-1, round(lat*4)/4+1+step,step)
lon_range = np.arange(round(lon*4)/4-1, round(lon*4)/4+1+step,step)

smap_coords = podpac.Coordinate(time=('2016-03-17','2016-03-18','6,h'), lat=lat_range, lon=lon_range,
                       order=['time', 'lat', 'lon'])
o_smp1 = smap.execute(smap_coords)
```
What is very curious and concerning is that if I request two days instead of just one, as below, the data for the first day doesn’t match up. 
```python 
smap_coords = podpac.Coordinate(time=('2016-03-17','2016-03-19','6,h'), lat=lat_range, lon=lon_range,
                       order=['time', 'lat', 'lon'])
o_smp2 = smap.execute(smap_coords)
```

When requesting a specific time using:
```python
smap_coords = podpac.Coordinate(time=podpac.Coord('2016-03-17T18', delta='2,h'), lat=lat_range, lon=lon_range,
                       order=['time', 'lat', 'lon'])
o_smp = smap.execute(smap_coords)
```
I can also get data in time windows when there didn’t used to be data such as:
```python 
smap_coords = podpac.Coordinate(time=podpac.Coord('2016-03-17T12', delta='2,h'), lat=lat_range, lon=lon_range,
                       order=['time', 'lat', 'lon'])
o_smp = smap.execute(smap_coords)
```
(this gives the same data as 18h for this call, when I was expecting nan's). 

What is the default time window in which it looks for data?  Is the default using interpolation between nearest neighbor points, or just taking the closest value?  If I want the exact value in the AM or PM files, what function call should I use?

Thanks,
Rachel

**Comment by mlshapiro** [comment]
noting for #7

**Comment by mpu-creare** [comment]
Closing this because it will be handled in #195
