### ISSUE TITLE
Incompatibility with Matplotlib 3.9.0

### ISSUE THREAD

**Issue by dhinckley-creare** [creare-com/podpac#516]
**Description**
As of Matplotlib 3.9.0, the `matplotlib.cm.get_cmap` function no longer exists so podpac throws errors.

**Steps to Reproduce**
```
in an environment with matplotlib 3.9.0

instantiate a Style object to trigger the _validate_colormap function
```

**Expected Behavior**
No errors are raised

**Observed Behavior**
An error about the function `matplotlib.cm.get_cmap` not existing is raise

**Comment by mpu-creare** [comment]
Notes: 
* [x] Try to make backwards-compatible
* [x] ~~Add a unit test for style~~ Already had one.

**Comment by jdw-creare** [comment]
I'm just starting to run into this error in the testing I was doing.  @rparker-creare , if I end up with a commit that fixes this issue, would that help?  And if so, would you mind if I still leave the release process on your plate?

I found this documentation page that describes the drop-in replacements:
https://github.com/matplotlib/matplotlib/issues/20853

**Comment by jdw-creare** [comment]
https://github.com/creare-com/podpac/tree/hotfix/colormap_update 

https://github.com/creare-com/podpac/commit/b9aeaf34910e8b6b625d3ef8d30572c323e24298

**Comment by rparker-creare** [comment]
See pull request #518

**Comment by jdw-creare** [comment]
Thanks Roslyn!
