### ISSUE TITLE
make internal references to classes and modules consistent

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#56]
**Description**

In the codebase, we refer to classes and modules both at the absolute location (i.e. `from podpac.core.data.data import DataSource`) and their top level locations (i.e. `from podpac import DataSource`).

**Describe the solution you'd like**

We should make sure we are consistent with how we refer to modules

This will be a difficult merge, so we should do this at a time that makes sense. There will be no  change to the code behavior.

**Comment by jmilloy** [comment]
See #40

**Comment by mlshapiro** [comment]
closing in favor of #40 and #81
