### ISSUE TITLE
Node _base_definition not used in Node, but is used in subclasses (i.e. DataSource)

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#58]
**Description**

`_base_definition` inside the Node module is not used internally, but I do notice that DataSource uses it when it called `definition`. 

Should we make `_base_definition` a public class just so that this is more clear?  I understand that `Node().definition()` may be different from `DataSource().definition()`, but its strange that `Node().definition()` doesn't use `_base_definition()`

**Comment by mlshapiro** [comment]
@jmilloy @mpu-creare says that this is a question for you related to PR #55

**Comment by jmilloy** [comment]
I'm not sure how it is related to #55. You just want to take the underscore off? Sure. I think that would be better.

**Comment by jmilloy** [comment]
And, `Node.definition` doesn't use it because `Node.definition` is not implemented in the Node class -- it *must* be implemented by a subclass. It was helpful during development to have the NotImplemented exception raised with additional information, but now it may be more clear to remove that.

**Comment by mlshapiro** [comment]
ah I see - ok, yes then we can plan to take the `_` off since this is a public utility to be used by subclasses. I'll change to a feature and implement when its appropriate

**Comment by jmilloy** [comment]
I'm just going to do this right now.

**Comment by jmilloy** [comment]
Pushed with additional documentation. I also see what @mpu-creare means now with regard to #55, I'll put that in a new issue.

**Comment by jmilloy** [comment]
I moved too quickly, and *now* I actually see what @mpu-creare means with #55. I should not have pushed the change that I did. Let me try to revert.

**Comment by jmilloy** [comment]
Okay, this is fixed in #55.

**Comment by mpu-creare** [comment]
Apparently I'm way too slow. Let me know if you still have any questions.
