### ISSUE TITLE
Question: how does interpolation in time handle nan's?

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac#6]
If one asks podpac for data at a time that is intermediate between two of the native source time points, how does the interpolation handle nan's in one of the adjacent points?  Does it return nan? Does it give the nearest value present and not interpolate?

Thanks,
Rachel

**Comment by mlshapiro** [comment]
hope to answer with #7

**Comment by mlshapiro** [comment]
will add to notebook on interpolation

**Comment by jmilloy** [comment]
@mlshapiro What is the status of this issue? Is this simply a documentation issue, or do I need to keep desired changes in mind while working on the interpolation?

**Comment by mpu-creare** [comment]
Documentation only.

**Comment by mpu-creare** [comment]
This has now been documented as part of the interpolation docs.
