### ISSUE TITLE
OrderedCompositor caching and source_coordinates do not work

### ISSUE THREAD

**Issue by dsully1992** [creare-com/podpac#65]
**Description**
The compositor `source_coordinates` and `cache_native_coordinates` properties do not work.

- Using `cache_native_coordinates=True` will result in an error in the node caching method.
- Using `source_coordinates={some coordinate object}` will cause an error in `Compositor.iterOutputs`

**Steps to Reproduce**
```python
acoords = Coordinate(lat=(0, 1, 10), lon=(0, 1, 10), order=['lat', 'lon'])
bcoords = Coordinate(lat=(2, 3, 10), lon=(2, 3, 10), order=['lat', 'lon'])

a = NumpyArray(source=np.random.random(acoords.shape), native_coordinates=acoords)
b = NumpyArray(source=-np.random.random(bcoords.shape), native_coordinates=bcoords)
composited = OrderedCompositor(sources=np.array([a, b]), cache_native_coordinates=True, source_coordinates=acoords)
c = Coordinate(lat=0.5, lon=0.5, order=['lat', 'lon'])
composited.execute(c)
```

**Expected Behavior**
Native coordinates should be cached and iterOutputs should provide a generator of the outputs for OrderedCompositor's execute method.

**Observed Behavior**
The errors mentioned above occur

**Additional Notes**
For now, a failing test was written and disabled. It should be enabled when this is resolved.

**Comment by mpu-creare** [comment]
The problem with the above example is that source_coordinates should be the same size as the number of sources. It should also be a coordinate that uniquely describes one of the sources. So, let's fix it. 

```python
acoords = Coordinate(lat=(0, 1, 10), lon=(0, 1, 10), order=['lat', 'lon'])
bcoords = Coordinate(lat=(2, 3, 10), lon=(2, 3, 10), order=['lat', 'lon'])
scoords = Coordinate(lat_lon=[[0.5, 2.5], [0.5, 2.5]])

a = NumpyArray(source=np.random.random(acoords.shape), native_coordinates=acoords)
b = NumpyArray(source=-np.random.random(bcoords.shape), native_coordinates=bcoords)
composited = OrderedCompositor(sources=np.array([a, b]), cache_native_coordinates=True, 
                                                         source_coordinates=scoords)
c = Coordinate(lat=0.5, lon=0.5, order=['lat', 'lon'])
composited.execute(c)
```

In fairness. I did have to fix a few other bugs.

**Comment by mpu-creare** [comment]
7882bb7892c5eb6ddc7ea539b2a4d99d97030552
