### ISSUE TITLE
CoordSelect tests are incomplete and very slow

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#74]
**Description**
The CoordSelect tests in test_coord_select.py are currently just copied from the initial __main__ script. The test there needs to be updated, cleaned up, broken into units, and sped up.

**Steps to Reproduce**

Run the tests locally.

**Expected Behavior**

The tests run quickly.

**Observed Behavior**

test_coord_select.py :: TestCoordSelect :: test_coord_select is slow and eats up RAM.

**Additional Notes**
I think the speed/RAM issue is just the large Coordinates in the time expansion portion. The speed is definitely an issue, but it's not the only issue. This test needs a complete rework.

**Comment by jmilloy** [comment]
Speed issue fixed in 7176243

**Comment by jmilloy** [comment]
#385 also helped with the speed on this one.

**Comment by mpu-creare** [comment]
@jmilloy can I close this one?

**Comment by jmilloy** [comment]
Yeah, looks okay. Runs quick, 88% coverage (looks like `TransformTime` is not tested), that's good enough for this issue.

**Comment by mpu-creare** [comment]
Could you add an issue so we don't loose track of `TransformTime` testing?
