### ISSUE TITLE
Import/Export Conventions intra-module and for API

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#81]
**Description**
Currently different parts of the podpac module handle imports differently.

- in `podpac.core.data.datasource`

```python
# in podpac.core.data.datasource
from podpac.core.units import UnitsDataArray
from podpac.core.coordinate import Coordinate, UniformCoord
from podpac.core.node import Node
from podpac.core.utils import common_doc
from podpac.core.node import COMMON_NODE_DOC
```

- in `podpac.core.algorithm.signal`

```python
from podpac.core.algorithm.algorithm import Algorithm
```

- `podpac.core.node`

```python
from podpac import settings
from podpac import Units, UnitsDataArray
from podpac import Coordinate
from podpac.core.utils import common_doc
```

**Describe the solution you'd like**

- The `__init__.py` file in the root of the `podpac/core` remain empty
- All subdirectories in `podpac/core` use the `__init__.py` file to define ALL public module components located within them (i.e. `podpac/data/__init__.py` defines all exports from `datasource.py`, `interpolate.py`, etc)

**Sample Code**

1.  Node exports/imports:

- `COMMON_NODE_DOC`, `Node` defined in `podpac/core/node.py`
- then in `podpac/core/data/datasource.py`

```python
from podpac.core.node import COMMON_NODE_DOC, Node
```

2. DataSource export:

- in `podpac/core/data/__init__.py`

```python
from podpac.core.data.datasource import COMMON_DATA_DOC, DataSource
...
```
- then in `podpace/core/datalib/smap.py`

```python
from podpac.core.data import COMMON_DATA_DOC, DataSource
```

3. Coordinate export

- `in podpac/core/coordinate/__init__/py`

```python
from podpac.core.coordinate.util import make_coord_value
from podpac.core.coordinate.util import make_coord_delta
from podpac.core.coordinate.util import add_coord
...
from podpac.core.coordinate.coordinate import BaseCoordinate
from podpac.core.coordinate.coordinate import Coordinate
...
```

- in `podpac/core/node.py`

```python
from podpac.core.coordinate import Coordinate

```

**Notes**

- We could bump everything up a level to get rid of `core` so everything above looks more like:

```python
from podpace.coordinate import Coordinate
from podpac import Node
from podpac.data import DataSource
```

**Comment by mpu-creare** [comment]
When you do this keep in mind: 
* some things have to be imported without the 'from'
* e.g. settings need to be imported as `import podpac.settings`
    * the danger is `from podpac.settings import CACHE_DIR` makes  COPY, and if something changes a setting it doesn't propagate to the rest of the package. 
* The same goes for `ureg`

* Also please document this in the developer notes

**Comment by mlshapiro** [comment]
Documented in contributing.md in cbaa4985bbcf24246337577996b88523c3976ea5
