### ISSUE TITLE
Implement Coordinate Spec

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#84]
See https://github.com/creare-com/podpac/blob/develop/doc/source/developer/specs/coordinates.md

See also:

 * #2 Coordinate Groups
 * #3 Tests
 * #4 Docs
 * #45 User Guide
 * #53 Naming convention
 * #42 lat_lon order

**Comment by jmilloy** [comment]
For reference, useful notes here #54 related to the coordinate creation spec.

We expect to do no additional work on the developer spec itself, as it will be superseded by the actual implementation and its docs, tests, and user guide.

**Comment by jmilloy** [comment]
@mpu-creare quick question

We used to be able to pass the default ctype, etc once in the Coordinates constructor. That's not as easy anymore in the new spec because the 1d coordinates are explicitly instantiated.

You can still do this:

```
c = Coordinates([_cu_lat(0, 10, 10, ctype='point'), _cu_lon(0, 10, 10, ctype='point')])
```

But you can't do this:

```
c = Coordinates([_cu_lat(0, 10, 10), _cu_lon(0, 10, 10)], ctype='point')
```

Is that okay? I guess shortcut functions such as the ones that Jerry requested would still take a ctype argument and pass that on.

I *could* figure out a way to make it work... in Coordinates1d init I could store whether the ctype was explicitly set, and if not, then the Coordinate init could overwrite it. Is that worth it?

Or maybe we could allow the user to set a global default?

```
podpac.coordinates.default_ctype = 'point'
c = Coordinates([_cu_lat(0, 10, 10), _cu_lon(0, 10, 10)])
```

**Comment by mpu-creare** [comment]
Why can't you do 
```
c = Coordinates([_cu_lat(0, 10, 10), _cu_lon(0, 10, 10)], ctype='point')
```
Can't you just overwrite the ctype in the 1D coordinates in the constructor of the Coordinates? 

I suppose you'd want to be able to have different ctypes for different coordinates (i.e. time v.s. lat/lon), so you'd only want to overwrite if it hasn't been set... 

Traits has this nice feature where it will set a default the first time a variable is requested if it hasn't been set before. It's a little bit of logic, but there's a way for the `Coordinate` object to detect if this is true, and only overwrite the default if it hasn't been set... but you have to get into the guts of traits a bit... 

Either way, I think I'm not worried. If it starts to get annoying there should be a way to fix it down the line without breaking the interface.

**Comment by mpu-creare** [comment]
I think I figured out how to be a bit more concise. 

    I could figure out a way to make it work... in Coordinates1d init I could store whether the ctype was explicitly set, and if not, then the Coordinate init could overwrite it. Is that worth it?

So basically, that functionality already exists in traits. Don't worry about figuring it out for now, we can always do it later.

**Comment by jmilloy** [comment]
Okay, thanks. I knew that Traits wouldn't set the default until the trait was requested, but I didn't know you could easily check whether it had done that yet.
