### ISSUE TITLE
Require complete coordinates during evaluation

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#88]
We will throw an exception when a node is evaluated with missing coordinates dimensions.

 * For example, when a node with (lat, lon, time) coordinates is evaluated at only (lat, lon) coordinates, we will throw an exception.
 * The other option, which has been rejected, would be to expand the evaluation to all available time coordinates. If all available time coordinates are desired, the user should request the native coordinates and intersect them with the desired (lat, lon) coordinates before making the request. *We may need to provide an explicit tool to facilitate this, particularly for pipeline definitions, which would be a separate issue.*
 * A special case is nodes with stacked native coordinates. For example, when a node with stacked ('lat_lon_time') native_coordinates is evaluated with 'time' coordinates, we will only throw an exception if the lat_lon coordinates are not unique for each requested time coordinate. Otherwise, we will select only the time portion of the stacked coordinate.

Note that in the opposite case, when a node is evaluated with *additional* coordinate dimensions, those dimensions are simply added to the output and the data broadcast as necessary.

Adding additional dimensions and checking for missing dimensions (along with handling of the special case) will replace the `replace_coords` call in the `node.get_output_coords` method. The `Coordinate.replace_coords` method will be deleted.

**Comment by jmilloy** [comment]
@mpu-creare I don't believe we've got an issue for this yet. Please let me know if I've missed anything here. When we discussed this before, I proposed we remove the `replace_coords` function because it was confusing and was only used in this one location, and just implement this logic and check right there where it is used.

**Comment by mpu-creare** [comment]
The logic should probably go at the head of the `eval` function... probably in the base node class (requiring children to call super for these checks). 

But it's fine to lump this into the Coordinate refactor.

**Comment by jmilloy** [comment]
I suppose it doesn't make a big difference to me if it is implemented in the base node `eval` method (requiring `super().eval(coords)` calls) or in the base node `get_output_coords` method (requiring similar `self.get_output_coords(coords)` calls, which I think is how the child eval methods are currently implemented).

**Comment by jmilloy** [comment]
This is implemented in 1ad55ae. Needs to be tested. Some eval methods do not call `get_output_coords`; maybe they should.

**Comment by jmilloy** [comment]
This is completed in 395f535, including unit tests.
