### ISSUE TITLE
DOC: import syntax sanity check

### ISSUE THREAD

**Issue by mlshapiro** [creare-com/podpac#93]
@mpu-creare @jmilloy  I now realize I should have made a branch with the import spec, but can you please sanity check my spec in contributing.md in cbaa4985bbcf24246337577996b88523c3976ea5 and e4d126e13e37912217d0e214a619641ab5b0ce5c

I realized that my understanding of the python import system is not as good as it should be - does my spec actually work?  I was hoping to come away with a template that could be quickly implemented across the modules for how to reference within podpac.

**Comment by mpu-creare** [comment]
Based on the commits, are you suggesting a flat structure for the public API?

I'd prefer a somewhat hierarchical structure, at least for the nodes. The main reason for this in my mind is to separate the library components from the actual data source/algorithm implementation of components:
```
podpac.
    Node <--- used a lot by developers, very useful for isinstance checks etc.
    Coordinate <--- used a lot, should be at the root
    _ulat
   _ulon
   _...
    algorithm <--- algorithm nodes
    data
    compositor
    pipeline
    alglib
    datalib
    core <-- developer API goes here. i.e. any non-public functions, or rarely used utility functions etc.
```
I could be convinced that `algorithm`, `data`, `compositor`, `pipeline` should all go into a `nodes` "module", and the `datalib`, `alglib` could go into a 'lib' module, to simplify matters. 

But if everyone else likes the flat structure, I can be convinced.

**Comment by jmilloy** [comment]
I prefer the hierarchical structure. And I think it still makes sense to allow a natural mix of depths:

```
from podpac.compositor import Compositor
from podpac.datalib.smap import SMAP
```

@mpu-creare It sounds like you don't mind using this public API in the podpac source ie `from podpac import Node` isn't just for user code but for anywhere in the podpac source that you want to import Node?

**Comment by mpu-creare** [comment]
I just wrote a long comment and then convinced myself otherwise. I see no need for regular users to need `Node`. Let's keep it in core and refer to it using the full path. `podpac.core.node.Node`

**Comment by jmilloy** [comment]
What about `from podpac import Coordinate`? I'd provide that shortcut for users, but use `from podpac.core.coordinate import Coordinate` in the podpac source.

**Comment by mpu-creare** [comment]
Agreed.

**Comment by mlshapiro** [comment]
updated in fc7a5448693ccf7cdd1ccddb523fc7718cf90943

discussed this further with @mpu-creare 

the short explanation:

- public user API will be developed an curated in root `__init__.py`. This may include a level of submodules ( like `podpac.algorithm`) that group some advanced, but still public, imports.
- developer API follows the core directory so we don't have to do anything special
- all source code should use the full module path on imports (i.e. using the developer API)
