### ISSUE TITLE
Cache index used for SMAP queries on publicly availble S3 bucket (or similar)

### ISSUE THREAD

**Issue by drc-creare** [creare-com/podpac#98]
**Description**
When first using the SMAP datasource an index must be created, this requires many calls to the NASA SMAP servers and takes a long time. This calculation is the same for all podpac users and is therefore redundant.

**Describe the solution you'd like**
Alter the SMAP datasource so that in addition to being able to calculate this index and save/retrieve it from local disk, it can also retrieve it from a known internet resource (possibly a public S3 bucket)

**Additional context**
This publicly available SMAP index will likely need to be updated periodically. This requires a process running on a server somewhere. Should access to the S3 bucket be paid by the client via [AWS Requester Pays](https://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html)?

**Comment by drc-creare** [comment]
SMAP index updating on S3 can be done with recurring AWS lambda function.

We can set S3 bucket to be requester pays after some number of requests per month/day/hour. This functionality has not been confirmed but it likely to exist (or it could be via AWS lambda function which likely does have this kind of functionality).

**Comment by mpu-creare** [comment]
We're planning to implement #210 instead.
